### ISSUE TITLE
Construct Shop Window Hole.

### ISSUE THREAD

**Issue by PatrickJnr** [Facepunch/sbox-issues#1392] opened 2021-12-10 16:49 UTC
**Describe the bug**
Didn't know what to title this, but there is no clip/collision here, and you can fall through the map, been like this for a good while.

**To Reproduce**

Load into Construct
Look to the shop window
See black hole.
Fall through.

**Expected behavior**
No hole to be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/3267523/145610443-534e3ffe-5e68-4980-8fb8-6e5f53aa7031.png)

**Comment by DoctorGurke** [comment] 2021-12-10 17:05
duplicate of #1383

**Closed** 2021-12-10 17:28 UTC
Labels: bug
