### ISSUE TITLE
Access to InputRounter/ButtonCode for querying the entire keyboard

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#196] opened 2021-05-17 13:27 UTC
**What can't you do?**
Access any key on the keyboard, currently, we're locked off to anything defined in InputButton however it would be nice to have access to the entire keyboard and query for button states there too.

**How would you like it to work?**
```cs
public void HandleInput(ClientInput input)
{
	if(input.KeyDown( ButtonCode.KEY_PAD_2 ) )
	{
		/* ... */
	}

	if ( input.KeyPress( ButtonCode.KEY_PAD_5 ) )
	{
		/* ... */
	}
}
```

**What have you tried?**
N/A

**Additional context**

**Comment by garrynewman** [comment] 2021-05-17 13:29
What do you want access to the entire keyboard for?

**Comment by ogniK5377** [comment] 2021-05-17 13:30
Working on emulation within s&box and it's a pain to not have a proper keymap and relying on preset binds. Having a nicer layout makes it less awkward

**Comment by garrynewman** [comment] 2021-05-17 13:33
I don't have any plans to allow this. I feel like it encourages people to do things the wrong way and before long we'll end up with key binding dialogs for each gamemode. I think the buttons system we have for input is enough.

**Comment by DoctorGurke** [comment] 2021-05-17 13:37
Restricting the amount and variety of keys we can use will severely limit the kinds of gamemodes we can make. Think of gta 5 style helicopters via numpad acces or space Sims with complex ship controls and functions.
There definitely needs to be a better way than just giving us a dozen or so keybinds.

**Comment by ogniK5377** [comment] 2021-05-17 13:39
I think just expanding the keyset to a limited set could work, num pads would be more than enough for my use case. The typical emulation buttons as well could be added such as Z, X, C, V, Q, T

**Comment by rtm516** [comment] 2021-05-17 13:39
The point made on Discord was that they want to keep it all compatible with a controller hence the current system.
So in my opinion there should be a binding for every button on a controller so we have plenty to use.

**Comment by DoctorGurke** [comment] 2021-05-17 13:40
Can't expect of every gamemode that it has to be compatible with controllers.

**Comment by ogniK5377** [comment] 2021-05-17 13:41
No, it's a fair point, controller support is something that should def be considered. Didn't think of that

**Comment by DoctorGurke** [comment] 2021-05-17 13:42
It should be considered, but not every game style works on controllers and forcing gamemodes to make it compatible is yet again restrictive

**Comment by garrynewman** [comment] 2021-05-17 13:46
When you're making a gamemode that requires every key on the keyboard drop me a dm and we can work together on how to design around it.

**Comment by ischmal** [comment] 2021-08-11 19:28
Encouraging games to be just as playable on a controller as they are with a keyboard and mouse makes perfect sense.

However, doesn't this logic of _forcing_ "input-equality" mean joystick users should also be prevented from spinning indefinitely because such a movement isn't possible with a mouse?

A major part of PC gaming is the vast array of input devices we have to use, so why enforce the common denominator instead of giving people the ability to use each device to its fullest potential? 

Besides, we know overly-complicated gamemodes aren't going anywhere. Just, instead of a user-friendly key binding menu we'll have instructions for copying and pasting in a series console commands to achieve the same thing.

**Comment by xrayhunter-git** [comment] 2021-10-01 01:42
This relates with discussion others and I had: https://github.com/Facepunch/sbox-issues/discussions/420

I do believe that is very important for gamemodes to have variety in their inputs; if not then the variety gets thrown into other combinations or UIs. Forcing the developers to work around this problem, and eventually, this needs to be resolved at a higher level, meaning the engine level by Facepunch.

Now I can agree, that having random bindings that are anonymous; and that have their own custom panel that holds these custom key bindings. This would become extremely frustrating as a user. To remedy the problem is to have a key bindings panel that not only deplays S&Box's Default Key Binding Registry but also shows the **current** gamemode's keybinds as either a separate drop-down or as a category below the S&Box's.

Additionally, it's unfair to say, "gamemodes should never have 'custom keybindings.'" Because, if you look at Garry's Mod, tons of addons have custom keybindings; I remember it was a pain to do custom keybindings, but it was nonetheless there to support dynamic addons. An example of an addon from Garry's Mod that used custom keybindings was: LFS (https://steamcommunity.com/workshop/filedetails/?id=1571918906)

**Comment by ischmal** [comment] 2021-10-01 05:06
Well stated, Xrayhunter.  

While I have a ton of respect and admiration for Garry, I would also respectfully ask that he not appoint himself as the arbiter of what inputs are and are not important.

**Comment by garrynewman** [comment] 2021-10-01 08:08
We're never going to have a separate bindings panel for games. I feel strongly against it, it's horrible experience and it shouldn't be nessecary.

I do concede that there are uses for this for keyboard users. Ctrl + A for selecting all units in a RTS game etc. We should allow these kinds of hotkeys.

**Comment by SleepyMode** [comment] 2021-10-01 14:36
I think a lot of the backlash on allowing separate controls for each game come from the assumption that there's not going to be any sort of consistency among them and everyone will have to "learn" the new controls every time they play a new game, however, I think (as mentioned above by garry regarding selecting all units in RTS games, et cetera) there really is a common set of controls relevant to a specific genre of games.
Whether it'd be CTRL+A for selecting all units in an RTS game, or the classic Q/E lean mechanics in some slightly more advanced shooter games, it should be considered that a lot of people can almost naturally expect certain things to be bound to certain controls by default per-game and be modifiable.

It's a sort of difficult choice to start off because you're basically trusting the designers of the games within S&box to not make a crappy experience with custom controls (of any kind), but then again, I think that removing that option completely restricts good games from being made properly much further than it restricts bad games from being made.

**Comment by Alf21** [comment] 2021-10-01 19:37
Pro (Access to every key):
- Sbox don't have to moderate every requested Input for every gamemode
- API is clean, not overloaded with tons of key combinations
- Needed for quick map, team voice chat, group selection, in-game editor interaction (complex), etc.

Con (Key limitation):
- Bad devs can make bad UX (like they can make a bad game, or like they can just use the existing key limitation and build tons of hand breaking key combinations, what do you say against this?)

Imo, there shouldn't be a specific key detection, that leads to static things the user can't modify. Instead, it should be a layered system like it is currently:
- The user can bind functions to keys
- The dev can bind functions to keys (gamemode saved keys!, if the dev decides overriding a bound key, it's their gamemode and it's done with intention).
- The dev can detect, which command is pressed (+command, -command)

I would just like to have a constructive working through of this topic (not like shouting names in discord). Based or not, I think it's best to start with a Pro-Con list in order to get to the best solution. No matter what the solution is in the end.
Gonna extend this list based on the arguments I'm reading.

(Thanks @xrayhunter-git getting me to this issue.)

**Comment by AMastryukov** [comment] 2021-10-01 20:27
I would like a hybrid approach. I personally enjoyed the fact that there were predefined actions assigned to specific keys. By design, this is a good concept because it allows developers of game modes that have similar functionality to have unified controls. Additionally, players don't have to re-learn the entire control scheme, or rely on amateur gamemode developers to create the perfect UX for each gamemode.

However, there is a problem. For gamemodes that require uncommon controls or those that have differing importance for certain controls, this is a limitation. It's not difficult to imagine games where the player can't jump, or crouch, or games where the scoreboard is not that important and the TAB key could be used for something else (e.g. inventory).

I agree that having gamemode-based keybinding menus can be messy, and I would much rather have it all handled by Sandbox. I like @xrayhunter-git's suggestion of having custom gamemode key bindings displayed in Sandbox key bindings menu. I think it would be nice to have a global, generic keybinding system that exists now, and have the ability to override and add more keybindings for every gamemode that would be displayed directly in the Sandbox settings UI.

In the end, someone is going to make a shitty UX regardless of how restricted they are. Too little restrictions and we can end up with a nasty mess. Too many and we might end up with some gamemodes that use hacky solutions to work around the limitations. I think striking a balance in this regard is key.

**Comment by sanny-io** [comment] 2021-10-01 22:54
> To remedy the problem is to have a key bindings panel that not only deplays S&Box's Default Key Binding Registry but also shows the current gamemode's keybinds as either a separate drop-down or as a category below the S&Box's.

This makes the most sense to me. It gets rid of anonymous binds, and the binds menu becomes a single source of truth for everything related to binds. I disagree with you Garry that would be a horrible experience. That sounds like the optimal experience for both developers and players.

**Closed** 2021-11-14 05:07 UTC
