### ISSUE TITLE
S&box editor breaks semi-frequently

### ISSUE THREAD

**Issue by Weldify** [Facepunch/sbox-issues#2038] opened 2022-07-17 17:43 UTC
### Describe the bug

Around every 20 minutes of using the s&box editor (varies), the following error pops up in the console:
![1](https://user-images.githubusercontent.com/66477673/179417756-eaa945c4-2211-454b-bf5a-d178e2e8e6fc.PNG)
Launching a game after that error will break the editor:
![2](https://user-images.githubusercontent.com/66477673/179417861-782713d4-49e5-4716-a4d0-1bf7f9de09f5.PNG)
Some of the UI elements are gone, the sidebar with tools stops working, the window exit button doesnt work, etc.
While the editor mostly breaks, the game works just fine, although if you exit the editor by pressing the in-game exit button, it does close the window, but sometimes it leaves the process running so you have to go and terminate it by hand using the task manager.

### To Reproduce

Inconsistent

### Expected behavior

No breaking 

### Additional context

Windows 10, usually appears when I'm coding in Visual Studio

**Comment by mzegar** [comment] 2022-07-17 17:57
I think a wide range of things causes this issue. I have an issue here related to fetching types as the game mode loads in, which causes this issue after the first hot reload (I haven't tested it in a while, but I'm assuming it still happens). I think I also remember Trundler talking about how he was getting this issue completely unrelated to `GetTypes(...)` https://github.com/Facepunch/sbox-issues/issues/1857

**Comment by Weldify** [comment] 2022-07-17 18:00
I don't use `GetTypes()` either.

**Comment by trundler-dev** [comment] 2022-07-18 01:14
This is a duplicate of https://github.com/Facepunch/sbox-issues/issues/2010.

**Closed** 2022-07-18 08:10 UTC
Labels: bug
