### ISSUE TITLE
`Client.SendCommandToClient` blacklist.

### ISSUE THREAD

**Issue by carlsmei** [Facepunch/sbox-issues#533] opened 2021-07-30 19:37 UTC
**Describe the bug**

Client.SendCommandToClient doesn't have a blacklist, this **bug**(?) allows you to run 'quit' or 'unbindall' commands on any player.

**To Reproduce**

![Image](https://user-images.githubusercontent.com/47307437/127703340-ea00f4c7-d533-484e-8fb1-94d8f6becdb1.png)

**Expected behavior**

A blacklisted command should be ignored and reported to the client console for example.

**Additional context**

N/A

**Comment by TheBerkin** [comment] 2021-07-30 19:44
Duplicate of #351

**Closed** 2021-07-31 11:30 UTC
Labels: bug
