### ISSUE TITLE
Support exposing arrays and structs to Hammer

### ISSUE THREAD

**Issue by sndrec** [Facepunch/sbox-issues#2348] opened 2022-09-21 20:48 UTC
### For?

S&Box, Hammer

### What can't you do?

Currently, it is not possible to expose either an array or a struct on an entity to Hammer in a way that makes it useful.

### How would you like it to work?

A struct in hammer should appear as a collapsible list of each of the variables present within the struct.

An array should appear with its label, and a PLUS sign to add a new item to the list, which would then appear under the label for the array. An item in this array would have an X by it, allowing you to remove that item.

### What have you tried?

Defining these variables at the top of my entity class definition and then exposing them to hammer with the [Property] attribute.

A s&box developer confirmed this was not currently possible in the Discord server.

**Comment by robotboy655** [comment] 2022-09-21 20:55
Duplicate of https://github.com/Facepunch/sbox-issues/issues/1645

**Closed by robotboy655** 2022-09-21 20:55 UTC
Labels: feature, 🗺 Hammer
