### ISSUE TITLE
Fix transparency in Scene

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5455] opened 2024-05-03 19:54 UTC
### Describe the bug

Ever since the addition of Scene, transparency has not behaved as-intended.

### To Reproduce

1. Create a shader that will mask a png using the alpha channel (or have some sort of material with transparency)
![g6HAZqB](https://github.com/Facepunch/sbox-issues/assets/5159369/6ab5f900-8ddc-49a3-a229-5494f2e1aa63)
2. Create a material that uses the shader with a texture that has transparency
3. Create a GameObject with a ModelRenderer and supply any model with your material as the Material Override
4. Notice that the rendered model *will* have transparency, but instead of allowing you to see behind it, it actually draws through the entire world (so the blue you see where the alpha should be is actually the camera's clear colour)
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/4e8de7f3-e492-4b59-a68c-020c0a7a1e43)

### Expected behavior

You can achieve the expected behaviour by creating a component like the following but those who don't have inside-out s&box knowledge are not going to be able to figure this out on their own (and it's really un-intuitive).

(Ideally these flags could be toggled on the ModelRenderer or something similar.)

```cs
using Sandbox;

public sealed class FixTransparency : Component
{
	[Property] ModelRenderer modelRenderer { get; set; }

	protected override void OnUpdate()
	{
		if ( !modelRenderer.IsValid() ) return;
		modelRenderer.SceneObject.Flags.WantsFrameBufferCopy = true;
		modelRenderer.SceneObject.Flags.IsTranslucent = true;
		modelRenderer.SceneObject.Flags.IsOpaque = false;
	}
}
```

The component above gives the following results (only in play mode):
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/80028f6b-9e68-46f1-926f-06fb6e4e59ce)

**Comment by ShadowBrian** [comment] 2024-05-06 15:27
If you set a mesh's alpha to just under full it'll realize it's transparent and work, which is dumb but might point to what's wrong

**Comment by Gmod4phun** [comment] 2024-05-06 15:36
Isnt this just #4265 and #4360 again?

**Comment by MrBrax** [comment] 2024-05-06 16:57
the base material on the mesh has to be translucent for the engine to pick it up when overriding the material with a translucent one

**Comment by DevulTj** [comment] 2024-05-14 08:27
Duplicate of #4360

**Closed by DevulTj** 2024-05-14 08:27 UTC
Labels: bug
