### ISSUE TITLE
Soundscapes don't play + don't loop

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#2128] opened 2022-08-04 08:17 UTC
### Describe the bug

On compile run soundscapes appear to work sometimes but will not play when launching the map again. On times they do work they do not loop despite setting a looping sound.

### To Reproduce

1. Make new soundscape
2. Add a sound to it looping or otherwise
3. Add it as an entity in hammer
4. Make sure enabled and compile
5. Try to run it on a gamemode

### Expected behavior

Soundscape should play

### Media/Files

![d98c28154c1212317ad41298c0965dd7](https://user-images.githubusercontent.com/105941502/182798615-8b36282f-58e6-4e1f-81a8-ef603cd2ac13.png)
![b62e2e451e1c74706ed325774da75df5](https://user-images.githubusercontent.com/105941502/182798630-d9e7cb43-ae43-4f17-9d83-ad68160d586c.png)

**Comment by KingOfTheFBI** [comment] 2022-08-08 14:58
looks like it happens to snd_event_point too

**Comment by QuackCocaine** [comment] 2022-08-21 05:58
for me, I have to play the sound that's used beforehand and then when i go in game it will play

**Comment by robotboy655** [comment] 2022-10-28 17:37
The soundscape looping was fixed as far as I can tell, as for sounds not playing - duplicate of https://github.com/Facepunch/sbox-issues/issues/2068

**Closed** 2022-11-01 12:57 UTC
Labels: bug, review
