### ISSUE TITLE
SCSS left/right padding doesn't work with backdrop-filter for world panels

### ISSUE THREAD

**Issue by Fishvap** [Facepunch/sbox-issues#2143] opened 2022-08-09 01:17 UTC
### Describe the bug

When using SCSS, backdrop-filter seems ~~to not go all the way~~ to break constantly on text labels.

### To Reproduce

1. Create text label in SCSS and create the world panel
2. Add a background-color to the text label / add a background panel
3. Use backdrop-filter on the label / panel
4. Observe the right side of the text label

### Expected behavior

Background should be blurred all the way, not cut off at the end

### Media/Files

![Example of the bug](https://user-images.githubusercontent.com/90802279/183541623-e5ece17e-896c-47dc-9342-739b4b754872.png)
![code](https://user-images.githubusercontent.com/90802279/183541689-56de1300-21e5-4739-a395-04fe5b5423f6.png)

**Comment by cr4yz** [comment] 2022-08-09 03:03
Duplicate of #1866

**Closed by cr4yz** 2022-08-09 03:03 UTC
Labels: bug
