### ISSUE TITLE
VR Controller Haptics

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#991] opened 2021-09-27 00:38 UTC
VR controllers can vibrate. S&box needs this.

**Comment by walllable** [comment] 2021-09-27 00:51
duplicate of https://github.com/Facepunch/sbox-issues/issues/763

**Comment by gvarados1** [comment] 2021-09-27 00:59
These need to get added to https://github.com/Facepunch/sbox-issues/projects/7

**Closed** 2021-09-27 08:19 UTC
Labels: feature
