### ISSUE TITLE
Scene.Trace.Sphere (and other non Ray casts) returns SceneTraceResult that has incorrect .Normal which matches reversed direct of the ray instead of the surface normal of the collider

### ISSUE THREAD

**Issue by mmjr-x** [Facepunch/sbox-issues#6910] opened 2024-11-13 23:10 UTC
### Describe the bug

Scene.Trace.Sphere (and other non Ray casts) returns SceneTraceResult that has incorrect .Normal which matches reversed direct of the ray instead of the surface normal of the collider.

![Image](https://github.com/user-attachments/assets/c692b6d2-d9ee-4357-a9db-953f8f5525f6)
Here the sphere cast is visualized, cast from the world position of the green spheres, to (and hitting) the closest point on the box collider (top) and the plane collider (bottom). The Red arrow shows the SceneTraceResult's .Normal and the white arrow shows what it should be (this was computed by triangulating the SceneTraceResult's shape and finding the closest triangle to the hit and taking that normal).

![Image](https://github.com/user-attachments/assets/2b8c098c-38d5-4b8d-98c7-31aa487c3631)
Here a ray cast is visualized, it shows the correct .Normal (as the white and red arrow's overlap).

The shown arrows magnitudes can be disregarded as that was picked manually to be able to nicely visualize this.

While the image only shows this for the box and plane colliders (those gave the clearest visualization), I also tested this for all the other colliders and the same issue seems to be present for the other collider types.
I also tested this for the box and capsule casts, they give the same results as the sphere cast.
~~I also tested this for a sphere cast not hitting the edge of a triangle, and instead coming in at a fixed angle, there the results where the same.~~ Retested this and this is untrue, see my [image in the comments](https://github.com/Facepunch/sbox-issues/issues/6910#issuecomment-2477215777) below. 

Don't think it matters however this was tested in the editor using a components with Component.ExecuteInEditor and in the Update loop.

### To Reproduce

Have a collider
Cast a sphere trace that intersects with said collider at an angle not matching the hit's surface angle
Observe the SceneTraceResult's .Normal that is returned and see that that incorrect

### Expected behavior

The SceneTraceResult's .Normal that is returned should be the correct surface normal for Scene.Trace.Sphere and other non ray casts.

**Comment by aylaylay** [comment] 2024-11-14 06:56
This seems to be working as expected. The sphere is hitting the corner, this is desirable and some games rely on it. I've tested both with our trace solver and physics engine traces and both give this same result.

Do you know if there's any engines that give a different result in this situation?

**Comment by lolleko** [comment] 2024-11-14 07:18
Ahh I thought this:

> I also tested this for a sphere cast not hitting the edge of a triangle, and instead coming in at a fixed angle, there the results where the same.

meant it also happens when the trace hits the surface. If it always hits the edge first, I would also expect the edge normal. I know that  at least UE and Unity have the same behaviour.

**Comment by aylaylay** [comment] 2024-11-14 19:51
That's just the behavior of GJK, unreal does the same and I would bet unity does also. I would close the issue because it's working as intended so there isn't much we can do. Is this blocking you from doing something?

**Comment by mmjr-x** [comment] 2024-11-14 20:18
@aylaylay I'm building a generic component to detect if a point is inside or outside a collider (that works with any collider, and accounts for the direction vertices are facing). However, I solved most issues by calling Shape.Triangulate and then finding the closes triangle and its normal (then take a dot product to find out if the point your checking if facing towards of from the face). It works, however it is quite performance intensive.

Since you ask, the nicest solution would be if collider.FindClosestPoint would return a surface normal as well (perhaps using an overload and an out argument), however this is outside the scope of this issue (and is a feature request) so I fully understand if you have no time to look at that :)

I will wait a bit for your response, however in any case thank you for taking the time to look at this and responding to me! I will close this issue in some time.

**Comment by aylaylay** [comment] 2024-11-14 21:08
FindClosestPoint would also return corner normals because it's using GJK. And returning the normal is pointless because it's basically going to be (point - closest).normal

**Comment by aylaylay** [comment] 2024-11-14 21:12
Wouldn't it make more sense to request a function for collider.IsPointInside? (convex only)

**Comment by mmjr-x** [comment] 2024-11-14 22:34
@aylaylay Haha xD got kind of stuck in the mindset solving the lower level problem, but yea that would be great! :)

**Closed** 2024-11-15 08:11 UTC

**Comment by mmjr-x** [comment] 2024-11-15 15:37
Ah I see you closed this, no problem! :) Thanks for look at this in any case! Much appreciated! 🙏
