### ISSUE TITLE
[Hammer] Chamfer instead of Bevel 

### ISSUE THREAD

**Issue by MackenzieShirk** [Facepunch/sbox-issues#892] opened 2021-09-09 12:13 UTC
https://user-images.githubusercontent.com/9064885/132683786-f7ac997c-4c01-412b-8164-d4f94baab9c5.mp4

**What can't you do?**
Bevel will only create a ~45 degree angle between two perpendicular edges when used, no options for smoother curve that chamfer offers.

**How would you like it to work?**
Replace bevel with chamfer, chamfering with a low value of 1 will produce the same results as bevel, but with more functionality

**What have you tried?**
No proper alternative to chamfer

**Additional context**
https://gyazo.com/a6fb00a88adead0446a9727bd0927c6b

**Comment by robotboy655** [comment] 2021-09-15 18:45
Duplicate of https://github.com/Facepunch/sbox-issues/issues/217 ?

**Comment by MackenzieShirk** [comment] 2021-09-15 22:56
> Duplicate of #217 ?

Not quite the same thing, but that would be beneficial to include with this.

**Comment by aylaylay** [comment] 2021-12-14 11:30
This is now in, ported from dota tools

**Closed by aylaylay** 2021-12-14 11:30 UTC
Labels: feature, hammer
