### ISSUE TITLE
Event.Run<T> not passing arg0 to methods

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#94] opened 2021-05-03 18:31 UTC
**Describe the bug**

When running Event.Run<T>(string eventName, T arg0) arg0 does not get passed to methods with this event.

Running event:

```
var evt = new ChatEntryEvent()
{
	Chatter = ConsoleSystem.Caller,
	Message = message
};
Event.Run( SurvivalEvent.ServerChatEntry, evt );
```

Hooking into event:

```
[Event(SurvivalEvent.ServerChatEntry)]
public void ServerChatEntry( ChatEntryEvent evt )
{
}
```

Exception:

https://i.imgur.com/fi0gKgd.png

**Comment by Erlite** [comment] 2021-05-10 20:16
Funny that we both tried to add a chat event and were both met with the same exception (#129) ^^'

**Comment by FlorianLeChat** [comment] 2021-08-01 15:22
Any news? The bug remains but doesn't seem to create exceptions anymore, it just fails silently.

**Comment by Jac0xb** [comment] 2021-09-28 02:04
Can we please get a fix for this.

**Comment by garrynewman** [comment] 2021-09-28 10:14
Are you sure it's broken?

![image](https://user-images.githubusercontent.com/928843/135068321-f2796ea9-ee63-4c0e-b2d9-c5089ac74fd1.png)

![image](https://user-images.githubusercontent.com/928843/135068348-247be74e-0af9-4d08-9143-d7cd0ce500cc.png)

**Comment by Adesii** [comment] 2021-09-28 10:50
Just tested it myself. and it does seem to work fine.

But if a method has different amount of parameters it just fails silently instead of atleast throwing an error or run it but just with a single parameter for example.

**Comment by garrynewman** [comment] 2021-09-28 11:29
That's kind of by design, I don't really want events running that aren't targeted specifically

**Comment by Adesii** [comment] 2021-09-28 11:32
makes sense.

**Closed** 2021-09-28 11:34 UTC
Labels: bug
