### ISSUE TITLE
Viewmodel camera disables main camera post processing effects

### ISSUE THREAD

**Issue by KETALx** [Facepunch/sbox-issues#5226] opened 2024-03-19 15:45 UTC
### Describe the bug

adding viewmodel camera with clear color disables post processing effects.

### To Reproduce

![image](https://github.com/Facepunch/sbox-issues/assets/81901907/16b1ca82-c17b-416a-92c2-3da1e7c62fc9)
![image](https://github.com/Facepunch/sbox-issues/assets/81901907/a2dadf8f-ded6-41e2-b009-b3f9d29f8f91)
1. Create both viewmodel and main camera
2. Put postprocessing on main camera
3. notice that when viewmodel camera is enabled, postprocessing is disabled

### Expected behavior

Keep post processing with viewmodel

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/81901907/ebd1c177-3abb-4f7e-a259-6ed91877d584)
![image](https://github.com/Facepunch/sbox-issues/assets/81901907/6715cd8c-d6ed-45da-b939-8eb6b77f29df)

**Comment by MrBrax** [comment] 2024-03-20 11:15
#4827

**Comment by DevulTj** [comment] 2024-03-21 12:47
dupe of https://github.com/Facepunch/sbox-issues/issues/4827

**Closed by DevulTj** 2024-03-21 12:47 UTC
Labels: bug
