### ISSUE TITLE
Modeldoc culls bones unless an animation is present

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#101] opened 2021-05-05 02:11 UTC
**Describe the bug**

I was having problems getting attachment points to work, and after much debugging realized modeldoc was not compiling the skeleton until I included any animation.

**To Reproduce**

1. Go to modeldoc and create a new model.
2. Add some bones.
3. Compile and see nothing on the right side.
4. Try to modify bone culling, still no compiled skeleton.
5. Add a empty animation named anything.
6. Hit compile and now your skeleton appears.

**Expected behavior**

Bones shouldn't be culled by default.

**Additional context**

https://developer.valvesoftware.com/wiki/Half-Life:_Alyx_Workshop_Tools/Modeling/Model_Troubleshooting

There is a wiki page on the valve wiki that states bones will be agressively culled without modifying bone culling settings, but modifying "BoneCullType" doesn't seem to work. Even then I think it is more intuitive to have to opt into culling but as long as we don't need to insert empty animations I'm good.

**Screenshots**

Bones without animation result in no skeleton
![image](https://user-images.githubusercontent.com/13395306/117089886-ccb87280-ad24-11eb-9258-ab809c66bc79.png)

Add in the animation and now the skeleton compiles
![image](https://user-images.githubusercontent.com/13395306/117089910-d80b9e00-ad24-11eb-9723-5fe879bd2262.png)

**Comment by garrynewman** [comment] 2021-05-05 07:41
Maybe the bone needs to be used by part of the mesh. When I added bones to the rust pistol it didn't remove the bones, but I forced the mesh to be a child of the bone (which you probably want to do to make the bone useful anyway)

**Comment by garrynewman** [comment] 2021-05-15 08:30
can you explain the use case here. Should you be using attachments?

**Comment by aylaylay** [comment] 2021-05-15 08:34
This is working as intended. If your model has no skinning data, you don't want it to include a skeleton. Using RenderMeshFile you can select a bone to skin to which means you'll have valid skinning data and your skeleton will be included.

You probably should just be using attachments, I can't think of any use for having a skeleton with no skinning data.

**Comment by Jake-Rich** [comment] 2021-05-16 00:03
The problem afaik is you can't use attachment points without a skeleton & bones, which is how you end up with no skinning data but a skeleton.

**Comment by aylaylay** [comment] 2021-05-16 00:21
I'll test it but I'm pretty sure attachments work on a non skinned model. If not then it's a seperate issue.

**Comment by igniscitrinus** [comment] 2022-08-22 04:46
To expound on this, the Bone Culling Type inside the BoneMarkupList properties applies -only- when an animation is present, such as an EmptyAnim or a BindPoseAnim. This isn't necessarily an issue, but this behavior can easily lead to confusion.

**Comment by aylaylay** [comment] 2022-08-23 04:49
I can have another look at this but when I first looked it didn't make sense to keep bones around with no skinning data

**Comment by Fortune117** [comment] 2022-08-23 04:58
I had a use case: for the view model of some guns, there's a 'lead gun' bone, that isn't attached to anything in the base mesh. It's designed for a gun to be parented to it. I got around this by adding an attachment to that bone.

**Comment by aylaylay** [comment] 2022-08-23 05:02
From my testing, skeleton shows up if you have a mesh or an animation, I'm not sure why you'd have a model with no meshes or animations

**Comment by aylaylay** [comment] 2022-08-23 05:54
I can add this but again, I'm not sure what use is a model that just has a skeleton and nothing else

**Comment by DoctorGurke** [comment] 2022-08-23 06:04
I was under the impression that It'd cull bones even if there is a render mesh? So a mesh with a rig would get its Skelton culled unless there's an actual animation present

**Comment by aylaylay** [comment] 2022-08-23 06:09
Seems to work fine here

**Comment by aylaylay** [comment] 2022-08-23 06:11
Oh, it only doesn't work when the model has no skinning data

**Comment by igniscitrinus** [comment] 2022-08-23 06:14
> Oh, it only doesn't work when the model has no skinning data

It happens to meshes with skinning data that have any bones without weights assigned to them as well.
It's not a common use case, but meshes that use unweighted bones as hierarchical parents for weighted bones (e.g. forearm high and low twist bones being children of one forearm bone) is a technique that some artists use in their rigs. It seems unlikely to occur in development on character models that would have some form of animation attached to them, but it's more likely to affect a model whose skeleton is being driven entirely by scripts (whatever the use case may be)

**Comment by aylaylay** [comment] 2022-08-23 06:25
I've allowed it to keep bones even when there's no skinning data, let me know if that allows you to do what you need to do

**Comment by igniscitrinus** [comment] 2022-08-23 19:15
No issues in my particular use case now, don't know about others.

**Closed** 2022-09-15 15:55 UTC
Labels: bug, review
