### ISSUE TITLE
Can't play the game

### ISSUE THREAD

**Issue by soupnuts6061** [Facepunch/sbox-issues#6137] opened 2024-08-06 00:48 UTC
### Describe the bug

when i try to launch the game it shows this error even though i have steam open

### To Reproduce

1. open the game on steam

### Expected behavior

i can play the game

### Media/Files

![steamwebhelper_Osin0kOoh1](https://github.com/user-attachments/assets/1deb35f6-c27c-4297-a9d3-93ae034d0e39)

### Additional context

running windows 11

**Comment by handsomematt** [comment] 2024-10-28 09:06
this is probably fixed now, likely caused by having a steam emulator installed

**Closed by handsomematt** 2024-10-28 09:06 UTC
