### ISSUE TITLE
Player count set to 1 but console reports "SV: maxplayers set to 32"

### ISSUE THREAD

**Issue by JamesC01** [Facepunch/sbox-issues#782] opened 2021-08-24 19:19 UTC
**Describe the bug**
A random person joined one of my games. I thought maybe I forgot to put it on 1 player. I made another server, and checked the console, and it reports SV: maxplayers set to 32.

**To Reproduce**

Maybe a 1 player game, and check the console. It's near the start, if you clear it before starting a server.

**Expected behavior**
maxplayers should be set to the player count.

**Comment by Gmod4phun** [comment] 2021-08-24 20:05
Basically a duplicate of https://github.com/Facepunch/sbox-issues/issues/8

**Comment by robotboy655** [comment] 2021-08-24 23:53
Duplicate of #8

**Closed by robotboy655** 2021-08-24 23:53 UTC
Labels: bug
