### ISSUE TITLE
Playing scenes often breaks and requires one or multiple hard restarts of the editor.

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4249] opened 2023-12-19 06:14 UTC
### Describe the bug

Often times when opening the editor scenes won't play and under the game view the main menu will be open. exiting a game into the menu also breaks this so I guess the issue is both the menu being loaded under game view when it shouldn't on start up and being unable to return to your game once on the menu.

### To Reproduce

Open the editor in any project
Open the game tab
Instead of the current scene, you see the main menu
Press the play button 
Nothing happens and an error pops up every frame
or
Hold escape to exit your game
Hit play or try to click on the game again
Nothing happens

### Expected behavior

pressing the play button should load the current scene / game and starting the editor should not load the menu

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/94070205/2ecdb94d-5be9-4a9a-adf0-5ce687934d48)

### Additional context

error that occurs every frame when in play mode:
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.GameManager.Render()
   at Sandbox.GameMenu.GameMenuDll.OnRender()
   at Sandbox.EngineLoop.OnClientOutput()
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_OnClientOutput()

**Comment by CarsonKompon** [comment] 2023-12-19 06:20
Pretty sure this is a duplicate of https://github.com/Facepunch/sbox-issues/issues/4178

**Comment by garrynewman** [comment] 2023-12-19 08:58
Does this happen when switching projects or from the first start?

**Comment by CarsonKompon** [comment] 2023-12-19 10:56
Both in my experience

**Comment by DrakeFruit** [comment] 2023-12-20 03:49
both

**Comment by garrynewman** [comment] 2024-01-02 07:07
I suspect I fixed this last week

**Comment by CarsonKompon** [comment] 2024-01-02 13:21
It seems good to me 👍

**Closed** 2024-01-03 07:09 UTC
Labels: bug
