### ISSUE TITLE
Unable to click anything after Toggling console in Fullscreen mode in Dev-Tools

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#1774] opened 2022-04-27 08:12 UTC
**Describe the bug**
if you're in fullscreen and press ` when in dev tools and click anywhere it puts you back into full screen

**To Reproduce**

1. Load up sbox-dev
2. go fullscreen 
3. press `
4. try to click on something 

**Expected behavior**
Should allow you to click on the item but instead it puts you back into fullscreen

**Comment by KayaDLX** [comment] 2022-04-27 08:43
Duplicate of https://github.com/Facepunch/sbox-issues/issues/1611

**Closed** 2024-07-21 22:38 UTC
Labels: bug
