### ISSUE TITLE
Increase dynamic light limit

### ISSUE THREAD

**Issue by JoeEffect** [Facepunch/sbox-issues#1296] opened 2021-11-17 09:32 UTC
Describe the error

If we create more than 15 dynamic light sources, we get a constraint error.

Reproduce

Switch to sandbox mode (for convenience)

Create 15 or more lamps.

Or create 15 or more light sources per pixel in the hammer editor.

See the error?

**Additional context**
Will this be fixed closer to release? Or after release? Many people are concerned about this and are waiting for a solution, it will help for big maps, especially if we want to make the night very beautiful, lights, signage, and so on.

**Comment by Faxou42** [comment] 2021-11-17 11:55
duplicate of issue [497](https://github.com/Facepunch/sbox-issues/issues/497) july.
pls dont make a new issue for something that is already here.
will probably not be fixed before release, they have other + priorities

**Closed** 2021-11-17 13:14 UTC
Labels: bug
