### ISSUE TITLE
Materials using Complex shader always turn red when tinted any color

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#613] opened 2021-08-06 18:44 UTC
**Describe the bug**
Adding a tint to a Complex material causes the material to turn red in-game, regardless of tint color. Preview in Material Editor looks as expected.

**To Reproduce**

1. Create a material with the Complex shader.
2. Add any tint color.
3. Set "Model Tint Amount" to 1.
4. Apply the material to a RenderEntity in-game.
5. Material renders with red tint in-game.

**Expected behavior**
The material should render with the expected tint color.

**Screenshots**
[Video](https://i.imgur.com/SQfIANO.mp4)

**Additional context**
1. I have only tested this under RenderEntities so far, so I'm unsure whether this issue extends to ModelEntities or map materials.
2. I have verified that this bug occurs regardless of the presence of a dynamic expression on the tint value.

**Comment by aylaylay** [comment] 2021-08-13 03:44
I have pushed a fix for this although only tested with Complex shader materials, it still may break with other shaders because of the way this was designed in a recent change.

**Closed** 2022-05-16 02:17 UTC
Labels: bug
