### ISSUE TITLE
Add capsule and rect lights to scene

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4999] opened 2024-02-29 05:38 UTC
### For?

S&Box

### What can't you do?

Since the entity system was removed, I seem to have no way of placing capsule and rectangle lights in game. 

### How would you like it to work?

I would like to be able to either instantiate them in the scene through code as I would any other SceneLight, or to place the appropriate component on a GameObject.

### What have you tried?

For now I'm just placing point lights at the midpoint of where I would like to place a capsule or rect light.

**Comment by Gmod4phun** [comment] 2024-02-29 07:30
Isn't this duplicate of #4452 ?

**Closed** 2024-02-29 10:11 UTC
Labels: feature request
