### ISSUE TITLE
Bring back DebugOverlay functionality to Gizmos

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4474] opened 2024-01-13 21:41 UTC
### For?

S&Box

### What can't you do?

As confirmed by Garry, gizmos can also be used to replace the old DebugOverlay, but right now it's missing the ability to make the gizmo persist for a set amount of time.
This is useful for stuff that last a tick but you still need to debug, something like dealing damage, animation events, sounds being played etc...

### How would you like it to work?

Just adding a final parameter for each gizmo defining the amount of seconds the gizmo is going to persist for. Just like it used to be with DebugOverlay.

### What have you tried?

The only alternative right now is implementing your own debug methods or creating a system to get gizmos to run every tick through custom classes.

**Comment by DevulTj** [comment] 2024-01-13 21:43
Duplicate of https://github.com/Facepunch/sbox-issues/issues/4285

**Closed by DevulTj** 2024-01-13 21:43 UTC
Labels: feature request
