### ISSUE TITLE
Material Editor always crashing sbox on saving new material

### ISSUE THREAD

**Issue by TheGetHuber** [Facepunch/sbox-issues#1782] opened 2022-05-02 11:47 UTC
Every time i want to save my new material in whatever folder material editor always crashing whole sbox. I've checked the logs, so this is what i find there: 
2022/05/02 14:39:08.995	AssetSystem	On-demand recompile of asset materials/cringe.vmat	
2022/05/02 14:39:08.995	AssetSystem	 -> reason: Invalid Dependency Information	
2022/05/02 14:39:08.995	AssetSystem	Recompiling resource asset: 'materials/cringe.vmat'	
I've tried to use contentbuilder.exe for compiling the .vmat file but it doesnt want to compile material. Whole log of compiling:

//====//

G:\Steam\steamapps\common\sbox\addons\koth_sawmill>..\..\bin\win64\contentbuilder.exe -b -o -nop4 -v -f
//------------------------------------------------------------
// Valve Content Builder ( Build : Apr 28 2022 )
// Copyright (c) Valve Corporation, All rights reserved.
//------------------------------------------------------------

Command Line:
  ..\..\bin\win64\contentbuilder.exe -b -o -nop4 -v -f

Working Directory: G:\Steam\steamapps\common\sbox\addons\koth_sawmill
Mod:               core @ "G:\Steam\steamapps\common\sbox\core"
Operation:         Force-building content and deleting orphans
Verbosity: high
Building:          All
Excluding:         None

Initializing app systems...
Done in 0.10 seconds.
Finalizing build list...
1 assets need to be built

Error: Failed to compile materials/cringe.vmat
--------------------------- OUTPUT ---------------------------
- addons\koth_sawmill\materials\cringe.vmat
  +- addons\koth_sawmill\materials\cringe_png_c4de8aac.generated.vtex

Exited with code -1073741795.
Command Line: resourcecompiler.exe -f -dxwarp -testmode -ignorecontentasserts -unbufferedio -useforcedirtyfile -i G:/Steam/steamapps/common/sbox/addons/koth_sawmill/materials/cringe.vmat -outroot G:\Steam\steamapps\common\sbox\.source2\contentbuild_1\A9E7EA7_0\game -threads 1
Run time: 0m:2s
--------------------------------------------------------------

No files found to merge from "G:\Steam\steamapps\common\sbox\.source2\contentbuild_1\A9E7EA7_0\game"!
Merging compile results: 1/1 (100.0%) in 0m:0s
Deleting temp files...

The following assets failed to compile:
  materials/cringe.vmat

Finished - 0 OK - 1 FAIL - 0m:3s

//====//

Path to the game hasnt got any cyrilic and ect. symbols

**Comment by ogniK5377** [comment] 2022-05-02 15:39
Can you please provide the actual material & use the issue format too?

**Comment by TheGetHuber** [comment] 2022-05-02 18:02
actual material is like what? .vmat files that it creates?

**Comment by TheGetHuber** [comment] 2022-05-02 18:16
Ok, reproduction steps... Firstable i launch Material Editor, then im pressing on "New" button, then im not changing anything (changin shader will not do anything) and pressing "Save" button, then im choosing "koth_sawmill/materials" folder, giving it random name, then pressing "Save". Material Editor is lodaing something, creating the .vmat file and right in that moment it crashes.
This is what .vmat contains:
`// THIS FILE IS AUTO-GENERATED

Layer0
{
	shader "vr_simple.vfx"

	//---- Color ----
	g_flModelTintAmount "1.000"
	g_vColorTint "[1.000000 1.000000 1.000000 0.000000]"
	TextureColor "materials/default/default_color.tga"

	//---- Fade ----
	g_flFadeExponent "1.000"

	//---- Fog ----
	g_bFogEnabled "1"

	//---- Lighting ----
	g_flDirectionalLightmapMinZ "0.050"
	g_flDirectionalLightmapStrength "1.000"

	//---- Metalness ----
	g_flMetalness "0.000"

	//---- Normal ----
	TextureNormal "materials/default/default_normal.tga"

	//---- Roughness ----
	TextureRoughness "materials/default/default_rough.tga"

	//---- Texture Coordinates ----
	g_nScaleTexCoordUByModelScaleAxis "0"
	g_nScaleTexCoordVByModelScaleAxis "0"
	g_vTexCoordOffset "[0.000 0.000]"
	g_vTexCoordScale "[1.000 1.000]"
	g_vTexCoordScrollSpeed "[0.000 0.000]"
}`

**Comment by TheGetHuber** [comment] 2022-05-02 18:17
when i tried to use custom texture it crashes too

**Comment by ogniK5377** [comment] 2022-05-03 09:03
Unable to reproduce, provide a mdmp file & your computer specs

**Comment by TheGetHuber** [comment] 2022-05-03 10:20
idk how to create mdmp file, i dont have such a file in sbox.
computer specs:
Intel Xeon E5450 3GHz 4Cores
DDR3 8GB ram
nVidia GTX 760 Ti 2 GB
1.5 Tb drive with sbox

**Comment by TheGetHuber** [comment] 2022-05-03 10:22
2 or 3 month ago i had a project in sbox. so i could use material editor without any crashes and ect. but now how you can see i cant.

**Comment by aylaylay** [comment] 2022-05-03 10:28
Likely using a pirate copy. We can't reproduce so closing this.

**Closed by aylaylay** 2022-05-03 10:28 UTC

**Comment by TheGetHuber** [comment] 2022-05-03 10:30
> 

![изображение](https://user-images.githubusercontent.com/69822538/166438562-c39a0cc0-bb5a-4b89-9e76-b7bd113b9871.png)
if you can tell me where i can find that mdmp file then i will give you it. i dont use the pirate copy of sbox. here is a screenshot of it in my steam library

**Comment by KayaDLX** [comment] 2022-05-03 11:36
Next time you crash you will have a mdmp file in the root folder of sbox. When you launch the game it gets automatically deleted.
