### ISSUE TITLE
entities parented to ent_path_platform freeze and crash

### ISSUE THREAD

**Issue by ALIEN31ITA** [Facepunch/sbox-issues#973] opened 2021-09-23 18:40 UTC
**Describe the bug**
if you parent entities to the ent_path_platform with a model and compile the changes, the map will refuse to load, resulting a freeze, folowed by a crash. tested with ent_door with a model

**To Reproduce**

1. Create an ent_path_platform and something to parent it.
2. go to the object u want to parent it, and parent it to the platform.
3. Compile the map.

**Expected behavior**
The Entities/Doors shouldn't crash the game.

**Additional context**

**Comment by robotboy655** [comment] 2021-09-24 15:55
Cannot reproduce this. It was possibly fixed by other recent changes. If it still happens for you on the most recent version of the game, please attach a map file that reproduces the issue or the `.dmp` file generated next to the game's `.exe` on crash.

**Closed** 2022-01-10 15:56 UTC
Labels: bug
