### ISSUE TITLE
Volumetric fog not working?

### ISSUE THREAD

**Issue by Pacific939** [Facepunch/sbox-issues#1237] opened 2021-11-08 02:44 UTC
Does Volumetric Fog not work? i tried to replicate some Volumetric Fog from Half Life Alyx in the S&Box Hammer Editor so i could use it in S2FM and i cant seem to get it to work, it should work like how it did in HLA right?
![Screenshot 2021-11-07 102457](https://user-images.githubusercontent.com/93893876/140676009-012c5042-12fa-4b9f-b87e-ac392b8e62ee.png)
![Screenshot 2021-11-07 102921](https://user-images.githubusercontent.com/93893876/140676011-63a37a6c-ab6f-4ee6-9f4f-55e5c3af2dd4.png)

here's how it worked in HLA, same settings on all the entity's object properties and it works
![Screenshot 2021-11-07 102910](https://user-images.githubusercontent.com/93893876/140676117-5e8df692-db2f-44e1-8488-4933c5c666da.png)
![Screenshot 2021-11-07 102626](https://user-images.githubusercontent.com/93893876/140676118-258a004c-f6b8-48e2-94e4-63558bb06ef2.png)

**Comment by CrazyBloo** [comment] 2021-11-08 02:49
Baked fog has been broken for a while, need to set it to dynamic

**Comment by Pacific939** [comment] 2021-11-08 02:56
> Baked fog has been broken for a while, need to set it to dynamic

I see, how do i set it to dynamic?

**Comment by bakscratch** [comment] 2022-03-14 18:31
Duplicate of #332

**Closed by bakscratch** 2022-03-14 18:31 UTC
Labels: bug
