### ISSUE TITLE
Black screen after selecting a game

### ISSUE THREAD

**Issue by yunes-0840** [Facepunch/sbox-issues#4460] opened 2024-01-12 03:26 UTC
### Describe the bug

Whenever I try getting into a game, s&box gives me a black screen while also locking my mouse to the middle of the screen.
It is possible to get back to the main menu if I remove the window focus off s&box and press on the X quickly enough that it doesn't lock my mouse to the middle again.

Restarting or re-installing the game doesn't work.

### To Reproduce

Select any game

### Expected behavior

that shouldn't happen

### Media/Files

![black_screen](https://github.com/Facepunch/sbox-issues/assets/68710005/a7d04bff-297c-4f3e-9192-e41ab8d1c4c8)
![getting_out_of_this_curse](https://github.com/Facepunch/sbox-issues/assets/68710005/9b8ffcaa-787c-4a3e-9e75-87a6e9f9280a)

### Additional context

-Custom Windows 11 ISO
-i5-10400F
-AMD RX 6750 XT
-1x16GB DDR4 2666MHz
-Game is in a 1TB NVMe ssd

**Comment by peter-r-g** [comment] 2024-01-12 03:56
Most likely #4415

**Comment by yunes-0840** [comment] 2024-01-12 05:21
![image](https://github.com/Facepunch/sbox-issues/assets/68710005/010e7d7c-998c-497d-8e65-b05d71ce1413)
same issue on staging branch, except it's another colour now and it looks pretty

**Comment by yunes-0840** [comment] 2024-01-12 05:22
also, most of the games I've tried entering with the main branch aren't even in the staging branch

**Comment by garrynewman** [comment] 2024-01-14 11:22
Yeah this is a duplicate of https://github.com/Facepunch/sbox-issues/issues/4415 and then  https://github.com/Facepunch/sbox-issues/issues/4398

**Closed by garrynewman** 2024-01-14 11:22 UTC
Labels: bug
