### ISSUE TITLE
Custom UI cursors

### ISSUE THREAD

**Issue by suiramdev** [Facepunch/sbox-issues#758] opened 2021-08-22 14:52 UTC
**What can't you do?**
It is barely impossible to display a cursor with a different style than the default one.

**How would you like it to work?**
Like it does on CSS, developers can add a `url` attribute to cursors.
`cursor: url(), pointer;`

**What have you tried?**
I have tried several ways to get a custom cursor, firstly by displaying a panel that follows the mouse position.
However, this requires the pointer events to be set to `all` and so displays the default cursor on top of the panel.

And finally, I tried adding an `url` attribute to the cursor, which the wiki says is not yet possible.

_I know you like adding new UI stuff Garry, and this is one of the coolest (or not)_

**Comment by garrynewman** [comment] 2021-08-22 14:53
Duplicate of #66

**Closed by garrynewman** 2021-08-22 14:53 UTC
Labels: feature
