### ISSUE TITLE
Scene Change does  close Server 

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#5577] opened 2024-05-30 21:05 UTC
### For?

S&Box

### What can't you do?

changing the scene && server still online , so every player who connected , stays in the network , and get witin the scene

### How would you like it to work?

that you can choose either its changing the scen within the players or not

### What have you tried?

scenechange and that all players get into the map or making it with connectip nothing works

**Comment by Gmod4phun** [comment] 2024-05-30 21:19
duplicate of #4949

**Closed** 2024-05-30 21:54 UTC
Labels: feature request
