### ISSUE TITLE
Some elements in asset browser sidebar + prefabs in hierarchy turn invisible when interacting with them

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#4340] opened 2023-12-31 10:32 UTC
### Describe the bug

Some elements in the asset browser sidebar turn invisible when you hover over them.
Prefabs in the hierarchy turn invisible when you select them.

### To Reproduce

asset browser
1. Hover over elements on the asset browser sidebar.
2. Some will randomly disappear.
____
prefabs
1. Put a bunch of prefabs in the hierarchy.
2. Select a prefab. 
3. Itself and all prefabs below it will disappear in the hierarchy. 

### Expected behavior

The UI elements should not turn invisible.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/91832803/a2903872-e662-40d7-af30-581002c53a39

**Comment by garrynewman** [comment] 2023-12-31 12:58
Duplicate of #4342

**Closed by garrynewman** 2023-12-31 12:58 UTC
Labels: bug
