### ISSUE TITLE
Events seem to be broken when arguments are supplied in certain instances

### ISSUE THREAD

**Issue by deadmonstor** [Facepunch/sbox-issues#623] opened 2021-08-07 15:13 UTC
**Describe the bug**
Events seem to be broken when arguments are supplied in certain instances. Sometimes erroring and other times doing nothing.

**To Reproduce**

1. Use this sandbox mode 
[https://github.com/deadmonstor/sandbox](https://github.com/deadmonstor/sandbox)
2. Type "testevents" in console
3. See that one errors and the other one does not fire.

**Expected behavior**
All 3 should fire successfully, not sure about the last one however because it has the same number of args as the other event with the same name.

**Screenshots**
[https://i.imgur.com/qOqCb3m.png](https://i.imgur.com/qOqCb3m.png)

**Additional context**
I did check this is the same on client/server. I think I know why it is erroring however I have no clue why it would not send the other ones

**Comment by FlorianLeChat** [comment] 2021-08-07 15:28
There is already a similar issue (#94) and I have experienced the same thing like you.

**Comment by deadmonstor** [comment] 2021-08-07 15:30
> There is already a similar issue (#94) and I have experienced the same thing like you.

hmm maybe yeah, this seems to work if you are in the same file now. Only broken in different files right now

**Comment by garrynewman** [comment] 2021-08-08 10:18
Duplicate of #94

**Closed by garrynewman** 2021-08-08 10:18 UTC
Labels: bug
