### ISSUE TITLE
box-shadow being clipped when using overflow

### ISSUE THREAD

**Issue by louiefox** [Facepunch/sbox-issues#397] opened 2021-06-24 23:21 UTC
**Describe the bug**
Box shadows are hidden when using overflow hidden/scroll etc.

**To Reproduce**

1. Create a box-shadow on a panel inside of a panel with overflow hidden on.
2. If shadow goes beyond parents bounds then it will be hidden.

**Expected behavior**
Shouldn't be clipped.

**Screenshots**
![image](https://user-images.githubusercontent.com/16431607/123344108-0ea6ad80-d54b-11eb-9d04-196352b580be.png)

**Comment by garrynewman** [comment] 2021-06-28 13:03
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by louiefox** [comment] 2021-06-28 14:58
This still seems to be an issue.

**Comment by garrynewman** [comment] 2021-06-28 15:21
Where is the overflow? If it's on the box's parent - it's going to clip. Can you show me what you're doing?

**Comment by louiefox** [comment] 2021-06-28 15:24
```
    .playerlist {
        width: 100%;
        height: 100%;
        overflow: scroll;
    }

    .playerentry {
        width: 100%;
        margin-top: 5px;
        background-color: $theme-background;
        box-shadow: 0 0 5px black;
        border: 2px solid $theme-foreground;
        border-radius: 8px;
        align-items: center;
        cursor: pointer;
        transition: all 0.1s all;

        &:hover {
            border: 2px solid $theme-accent;
        }
    }
```

Player entry is the panel with the red shadow and player list is the parent with overflow scroll.

**Comment by garrynewman** [comment] 2021-06-28 15:28
Yeah this is expected - https://jsfiddle.net/qoLyedks/

**Comment by louiefox** [comment] 2021-06-28 15:54
Ah I see, I can just add padding to the list. Is this something that could/should be "fixed"?

**Comment by garrynewman** [comment] 2021-06-28 15:57
No, it's working as intended.

**Closed** 2021-06-28 16:02 UTC
Labels: bug
