### ISSUE TITLE
No CSS shapes by using borders

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#1023] opened 2021-10-01 19:03 UTC
Seems the border tricks are not working, not sure if intentional or not.

Code:
`.trapezoid {
	border-bottom: 50px solid red;
	border-left: 25px solid transparent;
	border-right: 25px solid transparent;
	height: 0;
	width: 125px;
}`

Current:
![image](https://user-images.githubusercontent.com/4988198/135673139-cb6703cb-f317-434a-8b2e-9fd9955b9ee7.png)

Expected Behavior:
![image](https://user-images.githubusercontent.com/4988198/135673272-6649d7c9-92fb-48e3-9902-3e55e39ef1c3.png)

**Comment by ogniK5377** [comment] 2021-10-02 12:33
Duplicate of #90

**Closed** 2022-03-15 00:01 UTC
Labels: bug
