### ISSUE TITLE
"Unable to load one or more of the requested types." Warning renders tools unusable

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#2061] opened 2022-07-25 19:51 UTC
### Describe the bug

While hotloading there's a chance that I receive a warning that says "Unable to load one or more of the requested types."
![image](https://user-images.githubusercontent.com/59583743/180859522-b8adf5a9-8931-43b3-a0f2-9b206ba16feb.png)
After that, all the tools (Entity List, Inspector, Performance), with the exception of the console, will become empty and won't respond to inputs, this includes the Errors List so I have no idea how to narrow it down.

I am forced to close S&box, but doing so won't actually end the process like it does normally, I'll have to navigate through the Task Manager to abort the sbox-dev.exe process.

### To Reproduce

I am not sure really, I'd say most of the time it happens when I'm on the menu and I received a compile error, then I fixed it and the game recompiles. I'm currently investigating and will report whenever I find a way to reproduce.

### Expected behavior

-

### Media/Files

[Log.log](https://github.com/Facepunch/sbox-issues/files/9184276/Log.log)

### Additional context

The attached log was in the menu after I fixed an error in my game.

**Comment by yuberee** [comment] 2022-07-25 20:09
I found a way to reproduce it:

1. Before opening the game, make sure you'll get a compile error in one of your active addons, I just add a random letter somewhere and save;
2. Open S&box and wait for all addons to compile, you'll eventually get the compile error;
3. Fix the error and save the file, recompiling the addon, you will initially get the warning saying "Unable to load one or more of the requested types";
4. Save the file again, recompiling the addon, and the tools will break.

https://user-images.githubusercontent.com/59583743/180863923-972db32e-68ed-4013-bd86-6cdfcd739038.mp4

**Comment by trundler-dev** [comment] 2022-07-25 20:14
Duplicate of #2010, repro steps match the ones in my comment.

**Comment by DevulTj** [comment] 2022-07-27 17:05
as @trundler-dev stated, this is a duplicate of #2010 - forward your comments there

**Closed by DevulTj** 2022-07-27 17:05 UTC
Labels: bug
