### ISSUE TITLE
Better Component Reordering

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#4857] opened 2024-02-19 01:48 UTC
### For?

S&Box

### What can't you do?

I currently cannot quickly and easily reorder components, you have to right click the component and select "Move Up" or "Move Down" to reorder it.

### How would you like it to work?

A drag and drop reorder system.

### What have you tried?

Crying to myself for a bit I suppose.

**Comment by DevulTj** [comment] 2024-02-20 12:30
Duplicate of https://github.com/Facepunch/sbox-issues/issues/4254

**Closed by DevulTj** 2024-02-20 12:30 UTC
Labels: feature request
