### ISSUE TITLE
Networking is fucked

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4507] opened 2024-01-17 23:00 UTC
### Describe the bug

I dunno whats up but networking for me and some others is completely broken, its not related to the project and will even happen on a completely blank scene once "Start hosting" is clicked

### To Reproduce

if you're lucky enough to have the bug, just click start hosting on any scene.

### Expected behavior

not broken

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/28588188/860c751c-3471-427f-8cda-9aeb84acfd1c)

**Comment by Retroeer** [comment] 2024-01-17 23:02
I also am getting this, if you want to try and reproduce it, just clone Walker and see if it's fucked or not, if it's fucked and giving you the same error just disable the network helper component and it'll fix itself

**Comment by garrynewman** [comment] 2024-01-18 05:13
I need more to go on than this.

@Xenthio - a screenshot of errors is really useless. Provide log files please.

@Retroeer - This seems to be having issues with [Sync] vars - what are you syncing?

**Comment by Xenthio** [comment] 2024-01-18 09:33
Oh whoops I meant to upload the log file, that and the screenshot was supposed to have the stacktrace of the actual error selected, my bad

**Comment by garrynewman** [comment] 2024-01-18 14:38
Assuming this is fixed now, please make a more specific, helpful report if it's not 

https://docs.facepunch.com/s/sbox-dev/doc/reporting-errors-2OTPIafqCJ

**Closed by garrynewman** 2024-01-18 14:38 UTC
Labels: bug
