### ISSUE TITLE
Screen panels break when there's multiple cameras in a scene,

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/sbox-issues#4816] opened 2024-02-16 09:13 UTC
### Describe the bug

A scene panel will not render when theres a camera of lower priority drawing on top of the main one, 

### To Reproduce

Create a screen panel,
Create 2 cameras (In my case my second one is for the viewmodel, it can render absolutely nothing at all and still break the hud)
Watch as the screenpanel will disappear when the second one is enabled

### Expected behavior

The screen panel should continue to draw ontop of everything, like how it normally functions.

**Comment by badandbest** [comment] 2024-02-16 09:55
Multiple cameras seem to break just about everything 😭

**Comment by DevulTj** [comment] 2024-02-16 10:34
Duplicate of https://github.com/Facepunch/sbox-issues/issues/4664

**Closed by DevulTj** 2024-02-16 10:34 UTC
Labels: bug
