### ISSUE TITLE
Hotloading doesn't work well with Visual Studio if the game is installed to a different drive

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/sbox-issues#262] opened 2021-05-27 19:28 UTC
**Describe the bug**
Bit of a weird one.

Hotloading doesn't work very well with Visual Studio if the game is installed to a drive other than C:/

Notably, spamming save on the file eventually causes a hotload (sometimes more than one, unsurprisingly.)

Interestingly, Rider does not have this issue.

Matt944 and I have experienced this issue - Matt changed the game's installation to C:/ and it fixed it for him.

**To Reproduce**

1. Install VS to C:/
2. Install S&box to another drive
3. Try to change a file
4. It should take quite a few spams of the save to trigger a hotload

**Expected behavior**

Hotloading should respond properly to a file save in Visual Studio.

**Comment by Jac0xb** [comment] 2021-05-27 19:39
I actually have experienced this and thought it was typical. I have all my steam games on a secondary larger SSD X:/ and sometimes it takes 2-3 re-saves to hotload.

**Comment by Damianu** [comment] 2021-05-28 21:30
Happened to me too, also broke breakpoints in my case.

**Comment by TheOpalium** [comment] 2021-07-08 05:37
I'm experiencing the exact same problem. My games are installed on a different drive than Visual Studio (2019) and hotloading doesn't trigger unless I either:

 - Spam save until it finally happens
 - Move any file into or out of my addon folder

**Comment by Asaduji** [comment] 2021-07-08 07:52
Same here, i had to switch to Rider to deal with it

**Comment by robotboy655** [comment] 2021-07-08 10:36
I actually have noticed this too, and I think it started not too long ago.

For me it detects a change but doesn't really recompile anything, just says `Compiling Menu` and that's it, not `Compiling [X/X]` or `Client hotloaded` popups.

![image](https://user-images.githubusercontent.com/3299036/124907807-6f97a200-df9d-11eb-9429-632c603ec4df.png)

**Comment by robotboy655** [comment] 2021-07-16 14:21
I added a hacky fix for this, let me know if that improves this for you too.

**Comment by TheOpalium** [comment] 2021-07-19 16:24
No difference on my end.

**Comment by deadmonstor** [comment] 2021-07-19 16:49
> No difference on my end.

By the looks of it, the fix was reverted by Garry here [https://commits.facepunch.com/387363](https://commits.facepunch.com/387363)

**Comment by AdamSai** [comment] 2021-08-06 19:57
It's also happening to me. I got both S&box and Visual Studio 2022 Preview installed on my D drive

**Comment by AdamSai** [comment] 2021-08-06 20:18
Installing S&box  on my C drive seemed to fixed the issue. But, my Visual Studio 2022 is still on my D drive

**Comment by Adesii** [comment] 2021-10-15 17:36
Gonna bump this issue. 
Since it makes using Visual Studio on a small C SSD drive pretty hard / near impossible.
i have a small SSD as my C drive and lots of big addons (mostly high definition textures etc.) so that would easily fill up that SSD.

some more info i figured out from testing:

installing VS 2020 on E drive (HDD) and sbox on E drive = hotloading after many spam saves, sometimes never.
installing VS 2020 on C drive (NVME SSD) and sbox on G drive (Sata SSD) = hotloading after many spam saves.
installing VS 2020 on C drive and sbox on C drive = perfect hotloading.
installing VS 2020 on C and sbox on C but making a junction for Addons onto G drive = hotloading after many spam saves.

**Comment by Phyremaster** [comment] 2023-09-03 11:19
Since my issue was closed as a duplicate of this, here's what I've gathered:
- This is only an issue when editing code with Visual Studio
- This is only an issue when saving an existing files; creating new files or deleting files triggers a hotload
- What matters is where the project files are stored
- The issue is generally most severe when Visual Studio and the project files are on separate drives of very different speeds
- In extremes, this can prevent hotloading on file edit-and-save completely

**Comment by 5tickman** [comment] 2024-04-17 14:11
I ran into this issue as well, the only difference being that everything is installed on my SSD C: drive. I have since switch to using Visual Studio Code. Everything is working as expected after switching to VS Code.

**Comment by Metapyziks** [comment] 2024-06-19 15:19
If anyone's still having this problem, could you reply with:

1. Which drive is VS installed on, is it SSD or HDD
2. Which drive is sbox installed on, is it SSD or HDD
3. Which drive is your project installed on, is it SSD or HDD

Then bonus points for following these steps:

https://github.com/Facepunch/sbox-issues/issues/5683#issuecomment-2178912348

**Comment by Metapyziks** [comment] 2024-06-21 15:36
Closing since this had the exact same symptoms as #5683, which is now fixed.

**Closed by Metapyziks** 2024-06-21 15:36 UTC
Labels: bug
