### ISSUE TITLE
Dragging components into field adds the wrong component

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4286] opened 2023-12-21 22:41 UTC
### Describe the bug

```cs
public class ComponentReferences : Component
{
	[Property] private DummyComponent Component1 { get; set; }
	[Property] private DummyComponent Component2 { get; set; }

	protected override void OnAwake()
	{
		Component1.DoSomething();
		Component2.DoSomething();
	}
}
```

```cs
public class DummyComponent : Component
{
	[Property] public string Text { get; set; }
	[Property] public int Number { get; set; }
	[Property] public Model ModelReference { get; set; }
	[Property] public ParticleSystem ParticleSystemReference { get; set; }

	public void DoSomething()
	{
		Log.Info( $"DummyComponent: {Text} , {Number}, {ModelReference}, {ParticleSystemReference}" );
	}
}
```

If you have a `ComponentReferences` component on a GameObject, and 2 `DummyComponent`s on the same GameObject, it will run the invoked function twice on the first component in the list.

![image](https://github.com/Facepunch/sbox-issues/assets/66768086/7edefebf-9e21-40d8-a34f-717d447f7315)

In this case it prints the following: 
```
04:37:20   GameMenu  [1] DummyComponent: Hello , 1, [Model{models/humans/heads/frank/frank.vmdl}](arg:0), [Particle System{particles/example/constrain_distance_example/constrain_distance_example.vpcf}](arg:1)
```

Whichever component appears first in the list will be called twice, after "Move Up"-ing the second component:
```
04:38:38   GameMenu  [1] DummyComponent: World , 238172371, [Model{models/editor/iv_helper.vmdl}](arg:0), [Particle System{particles/break/break.cardboard.vpcf}](arg:1)
```
See the "[1]" meaning it printed identical output twice.

### To Reproduce

1. Have 2 component references of the same type.
2. Call a function on both of them. (In my case I'm calling 2 particle managers to spawn 2 separate particle effects, but only the first one spawns)
3. Only one component will get called twice.

### Expected behavior

Both components have their functions invoked properly.

**Comment by dch-GH** [comment] 2023-12-21 22:57
This might actually be that simply any other component references get overwritten with the first one in the hierarchy, not just the function call. 
My setup: 
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/ea6f60ac-011c-4a78-9008-765d9f078e82)
```cs
public class SceneParticleManager : Component
{
	[Property] public ParticleSystem Template { get; set; }

        ...
 ```
```cs
public class Weapon : Component
{
	[Property] public SceneParticleManager Beam { get; set; }
	[Property] public SceneParticleManager Splash { get; set; }
    
	protected override void OnStart()
	{
		Log.Info( Beam.Template );
		Log.Info( Splash.Template );
        }
        ...
```
Logs the following: 
`04:56:17   GameMenu  [1] [Particle System{assets/particles/beam.vpcf}](arg:0)`
(Whichever component appears highest in the component list)

**Comment by Gmod4phun** [comment] 2023-12-21 23:01
How did you set the two components? By dragging the GameObject into the inspector or the component itself? I can imagine if you did it by dragging the GameObject, it finds the first (or last) component and uses that.

**Comment by dch-GH** [comment] 2023-12-21 23:06
> How did you set the two components? By dragging the GameObject into the inspector or the component itself? I can imagine if you did it by dragging the GameObject, it finds the first (or last) component and uses that.


![90KUFLN](https://github.com/Facepunch/sbox-issues/assets/66768086/815ebb97-2b88-4214-89a8-79a7b0260be7)
By dragging  the individual components themselves.  A workaround is to just put the second component on a separate child GameObject, not a fix though.

**Comment by Gmod4phun** [comment] 2023-12-21 23:08
Nice find. I doubt this is an intended behaviour.

**Comment by DevulTj** [comment] 2024-01-29 13:14
I realize this probably won't work for your exact use case. I was fixing something specific to using an inherited type. 

Needs more thought because as of right now all we're doing is storing the type name for the component. So maybe giving components IDs?

**Comment by MrBrax** [comment] 2024-01-29 13:59
are the components not stored in the array in the same position every time? can that not be used for identifying?

**Comment by DevulTj** [comment] 2024-01-29 14:02
> are the components not stored in the array in the same position every time? can that not be used for identifying?

I thought about that too, but it'll become a slog to have to maintain that list for all component references for a bunch of actions - moving components up/down, removing components, etc..

**Comment by dch-GH** [comment] 2024-01-29 22:33
> I've pushed something that should fix this - let me know if it's working for you.



> I realize this probably won't work for your exact use case. I was fixing something specific to using an inherited type.
> 
> Needs more thought because as of right now all we're doing is storing the type name for the component. So maybe giving components IDs?

Yeah still not fixed for me.
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/7b323047-c986-47a4-8fe2-467296f21635)
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/2a1e3d8c-2985-4fef-bc37-1ff0f8ac41af)
These use different particle effects but only the first one (the first component of that type to appear on the list) is referenced by both properties. So whichever one I "Move Up" the highest will be used twice instead of each of them separately.

**Comment by DevulTj** [comment] 2024-01-29 22:35
yup, this'll be fixed when a branch im working on is merged

**Comment by DevulTj** [comment] 2024-02-28 12:34
Depends on https://github.com/Facepunch/sbox/pull/1449

**Closed** 2024-03-14 18:14 UTC
Labels: bug
