### ISSUE TITLE
map command fails when sv_password isn't empty

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#132] opened 2021-05-10 21:38 UTC
**Describe the bug**

If `sv_password` is set local client will fail to create a game using `map` command

**To Reproduce**

Go to main menu
Put `sv_password password` in console
Put `map testmap` in console
It will fail to main menu

**Expected behavior**

When connecting to self should apply the server's `sv_password`

**Comment by Erlite** [comment] 2021-05-10 22:13
+1, can reproduce, happened to me as well earlier. Can't `restart` either.

**Comment by KingDavidW** [comment] 2021-05-11 23:44
As a workaround, set your password locally. It is rejecting the map command because it's rejecting the connection to your own server

`sv_password sandy
password sandy
map testmap`

**Comment by robotboy655** [comment] 2021-09-16 10:27
Should be fixed.

**Closed by robotboy655** 2021-09-16 10:27 UTC
Labels: bug, no-issue-activity
