### ISSUE TITLE
Modeldoc: ConfigAttachedModel

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#403] opened 2021-06-26 10:35 UTC
**What can't you do?**
The ability to use ModelDoc's ConfigAttachedModel, right now it doesn't seem there is a way of making the models show up in-game, only in the editor.

**How would you like it to work?**
A way to make the model show up in-game albeit through code or automatically.

![image](https://user-images.githubusercontent.com/4988198/123510292-4284ee80-d683-11eb-82fe-4babf0dff67b.png)

**Comment by TeKGameR950** [comment] 2021-09-15 11:36
The bot closed it but the issue is still there.

**Comment by TeKGameR950** [comment] 2021-09-15 12:17
Is there any other method to have a model inside another model ? So i can for example have a first person arms models, with a gun and build my viewmodel in modeldoc instead of having 2 times the gun & hands models. (World model & view model)

**Closed** 2021-12-01 19:25 UTC
Labels: no-issue-activity
