### ISSUE TITLE
Entity spawner in core for Hammer

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#1917] opened 2022-06-07 03:57 UTC
### For?

Hammer

### What can't you do?

I wanted to be able to spawn an entity using the `OnTrigger` output of a trigger entity but it looks like there isn't a good way yet.

I was told by other mappers that there used to be something called template entities but they were removed, so maybe a C# version of those would work.

### How would you like it to work?

An entity that can spawn other entity types via inputs from hammer.

### What have you tried?

I can write up some custom stuff for now, but I think a good generic use-case entity spawner would be a good feature to have.

**Comment by robotboy655** [comment] 2022-10-14 16:23
Duplicate of https://github.com/Facepunch/sbox-issues/issues/2097

**Closed by robotboy655** 2022-10-14 16:23 UTC
Labels: feature
