### ISSUE TITLE
Add Metadata to LobbyConfig

### ISSUE THREAD

**Issue by kEllieGit** [Facepunch/sbox-issues#6959] opened 2024-11-18 14:51 UTC
### What can't you do?

There is no way to add custom metadata to lobbies, for example if you want any sort of specific functionality for your game lobbies that S&Box currently does not provide, it is impossible to without asking FP to implement it.

### How would you like it to work?

Possibly a KeyValuePair in LobbyConfig for potential custom metadata

### What have you tried?

N/A

**Comment by Nolankicks** [comment] 2024-11-18 15:23
Dupe of https://github.com/Facepunch/sbox-issues/issues/6610

**Closed** 2024-11-18 17:22 UTC
