### ISSUE TITLE
Particles will not update visual when moving them around in scene

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#5716] opened 2024-06-25 01:53 UTC
### Describe the bug

When using the Legacy Particle System component the particle will not visually update when moving until you do something else like enabling disabling. A bit of a hassle if you are working with a lot of them and try to see where they are.

https://github.com/Facepunch/sbox-issues/assets/105941502/9bb19052-7df5-441a-9caa-80459844d8d2

### To Reproduce

1. Make Legacy Particle component
2. Try to move given particle 

### Expected behavior

Should update its visual as you move it but it will not

**Comment by aylaylay** [comment] 2024-06-25 02:17
Is this particle on asset party?

**Comment by aylaylay** [comment] 2024-06-25 02:24
Can you provide the particle files please?

**Comment by DoctorGurke** [comment] 2024-06-25 03:36
If this is your particle make sure you pin it to cp0

**Comment by KingOfTheFBI** [comment] 2024-06-25 15:30
> Can you provide the particle files please?

[assets.zip](https://github.com/user-attachments/files/15973754/assets.zip)
Here is an example that does it

**Comment by aylaylay** [comment] 2024-06-25 22:00
I think this is just because of how you're creating the particle, you need to add a Set Vec operator to move it to control point, right now you're only setting the position on initialization.

Maybe we can tell it to restart when transforming in editor for these situations?

**Comment by DoctorGurke** [comment] 2024-06-25 22:03
Sounds like a bad idea with how I've worked with particles over the years personally, you just need to add a movement lock to cp or any of the other 3 nodes that make it work. Might just be a legacy particle editor thing forever imho

**Comment by DoctorGurke** [comment] 2024-06-25 22:05
The origin is really just control point 0 for particles by default and you don't just want to reset a system when a cp moves I'd think

**Comment by aylaylay** [comment] 2024-06-25 22:20
This would just be in editor though, when you move a particle in editor you want to see where that particle is going to start playing from.

**Comment by DoctorGurke** [comment] 2024-06-25 22:23
Cp0 could be used differently in the particle system though in which case you'd want the proper preview and not have it reset to the new transform. "Moving a particle" is relative if you can decide which cp does what exactly in PET

**Comment by aylaylay** [comment] 2024-06-25 22:29
I'm not seeing how that's an issue when moving it in editor. It's a better user experience to restart the particle when you've moved it to a new location, it stops this kind of situation where you have to manually enable and disable.

**Comment by DoctorGurke** [comment] 2024-06-25 22:35
You can setup systems to hardcode a position in PET via set control point value nodes and use a different cp for the position initializer where cp0 (the object transform in editor) controls where a trail affect targets towards, or a child particle aims, or whatever really. 
In my book this is just a skill curve issue with the legacy particle tool, you need one node to fix this, we've used a ton of particles in rogue arena and the editor worked fine for it as long as the system is setup properly. In the end this is a huge data driven mess and at worse it'll further break legacy particle systems in weird and unknown ways that won't be apparent until somebody has some real specific particle setup

**Comment by aylaylay** [comment] 2024-06-25 22:39
I think you might be getting confused, when I say editor I mean scene editor, not particle editor

**Comment by DoctorGurke** [comment] 2024-06-25 22:40
Nope I gotcha

**Comment by DoctorGurke** [comment] 2024-06-25 22:43
Particles won't rotate along with their transform either without rotation lock on a node, it's sort of just how you gotta work with them

**Comment by aylaylay** [comment] 2024-06-25 22:44
That's fine. But when you're placing a particle in editor and only set position on init, it's desirable to restart to see how that particle is going to look at that location.

**Comment by DoctorGurke** [comment] 2024-06-25 22:49
You're saying restart the system if the position updates yea?

**Comment by aylaylay** [comment] 2024-06-25 22:51
Yes, only in scene editor when the game isn't running

**Comment by DoctorGurke** [comment] 2024-06-25 22:56
I fully get your point for a user friendly preview, but the problem is just that particle systems don't have to care about any actual position. 
The game object transform just feeds into cp0 which happens to be the default control point for position initializers, it could be anything though. A particle could use cp0 *velocity* for an effect, this would completely destroy the preview for that since it'd just be restarting the system and not getting a previous position for velocity.
In the end the quality of the particle preview comes down to the quality of the particle system implementation in PET, more so than the editor

**Comment by aylaylay** [comment] 2024-06-26 00:35
I think you're right in that this is more up to the user than something we should force. If you want the system to be moveable, add a position lock.

**Closed by aylaylay** 2024-06-26 00:35 UTC
Labels: bug

**Comment by aylaylay** [comment] 2024-06-26 01:09
@DoctorGurke If I was able to just do the same thing position lock node does when transforming in scene editor, would this be ideal?
