### ISSUE TITLE
[REGRESSION] Clicking on any thing in the inspector sets the current object to null

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#7030] opened 2024-11-25 17:30 UTC
### Describe the bug

Clicking on any thing in the inspector sets the current object to null

### To Reproduce

Click on anything in the inspector

### Expected behavior

Should work

### Media/Files

https://github.com/user-attachments/assets/b2b6b85e-6609-451e-8bee-e3d0352258c2

Video from Mapics, I've gotten the same thing, just too lazy to record.

**Comment by Retroeer** [comment] 2024-11-26 01:59
dupe of #7007, fix is to wiggle the inspector

**Comment by solwllms** [comment] 2024-11-27 14:36
dupe of #7007

**Closed by solwllms** 2024-11-27 14:36 UTC
