### ISSUE TITLE
Connecting to certain Gamemodes doesn't work.

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#510] opened 2021-07-28 08:49 UTC
**Describe the bug**

When finding a game of for example Speed-Dial. It takes very long to load and then it disconnects the connecting user.
Speed-Dial is currently unplayable because of this issue.

**To Reproduce**

1. Connect to a Server of Speed-Dial.
2. Stuck in the Loading Screen.
4. getting disconnected.

**Expected behavior**
Connecting to the Server like it was always the case. Not sure what changed for this issue to happen.

**Screenshots**

Stack trace of the Connecting process:

![1](https://user-images.githubusercontent.com/37816311/127290573-72e1ea87-ef7b-4777-8426-234656d0b7b4.png)

![2](https://user-images.githubusercontent.com/37816311/127290598-4716ea30-b02d-424e-b7cc-ca7dee94137a.png)

**Additional context**

we tested it with 4 members internally. each of which tried hosting/connecting. nothing worked.

note: It happens with other gamemodes too. Which work and which don't seem to be random or tied to the complexity of the gamemode.

**Comment by Geeknerd1337** [comment] 2021-07-30 16:06
![image](https://user-images.githubusercontent.com/15205856/127680680-f1632795-5748-4726-82f7-4cc31503383c.png)
![image](https://user-images.githubusercontent.com/15205856/127680690-83a21339-306e-44f7-8ed7-adb1f6ed755c.png)
![image](https://user-images.githubusercontent.com/15205856/127680693-cabef208-45ed-4ceb-acc7-04c6e8d00d49.png)
![image](https://user-images.githubusercontent.com/15205856/127680703-a7589c6d-0258-4f81-8f78-564a7845bcd2.png)

Just confirming this is happening with several other gamemodes and even other users.

**Comment by FlorianLeChat** [comment] 2021-07-30 16:17
I experienced the same issue when I wanted to create a game when the convar `sv_password` wasn't empty (I doubt it was related to this issue however).

**Comment by Acecool** [comment] 2021-07-30 16:36
If you connect and you do not have the map, you will be kicked because of missing map but you can't choose the server without using the server browser game-mode.

The sv_password is another ( and I just opened a polish / ease of use feature request for that )

These do not seem to be the case for you - you are being disconnected either by your client or the server...

Can you click on the errors and use ALT + PrintScreen to capture the entire window and show the stack-trace? for the red errors where it says SendMessage reliable failed with eresult ... and a few others?

**Comment by Geeknerd1337** [comment] 2021-07-30 16:40
![image](https://user-images.githubusercontent.com/15205856/127684672-4752a1f5-62e6-4e07-a7f9-a5355b59e58b.png)
 Just confirming this isn't an sv_password thing

![image](https://user-images.githubusercontent.com/15205856/127684749-5ea83557-0a5d-4e4e-a7af-42e0d7fc4cd0.png)

No stack trace prints for the error, unfortunately.

**Comment by Nebual** [comment] 2021-08-01 21:23
This is likely the same issue we've been discussing in https://github.com/Facepunch/sbox-issues/issues/287#issuecomment-869213359 - it's quite annoying, and seems to be reproducible by having at least 200kb of cs files (including comments) when clients try to join. That issue originally also affected the host, which was fixed, but the limit remains for clients.

**Comment by Alf21** [comment] 2021-08-01 21:28
[TTT Reborn](https://github.com/TTTReborn/tttreborn) has this issue as well:

![image](https://user-images.githubusercontent.com/11843790/127785790-5f9c5f5b-8170-4e03-8b24-f33119a8a664.png)

Ty for the hint @Geeknerd1337

**Comment by garrynewman** [comment] 2021-08-04 10:50
Duplicate of #287

**Closed by garrynewman** 2021-08-04 10:50 UTC
Labels: bug
