### ISSUE TITLE
Spawning GameObjects from OnDestroy while exiting play mode causes you to get stuck "editing" the Current Scene".

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4537] opened 2024-01-20 20:50 UTC
### Describe the bug

Says on the tin

### To Reproduce

1. Inside the `OnDestroy` override, spawn one or more GameObjects:
```cs
	protected override void OnDestroy()
	{
		base.OnDestroy();
		var go = Scene.CreateObject();
		go.Name = Time.Now.ToString();
	}
```
2. Be stuck in limbo:
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/bd131699-90df-46a5-b646-11c6b760b151)
3. Press F5 twice to actually get back to scene editing.

### Expected behavior

This can be avoided by the user by doing this:
```cs
	protected override void OnDestroy()
	{
		base.OnDestroy();
		if ( !GameManager.IsPlaying )
			return;

		var go = Scene.CreateObject();
		go.Name = Time.Now.ToString();
	}
```

But is probably more of a workaround, and only really works if you have some wrapper for instantiating objects from one place.

### Media/Files

[Log.log](https://github.com/Facepunch/sbox-issues/files/13999201/Log.log)
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/ea423eac-6b55-4329-9bb8-7280f5db16f3)

**Comment by kurozael** [comment] 2024-04-10 16:22
Duplicate of #4855

**Closed by kurozael** 2024-04-10 16:22 UTC
Labels: bug
