### ISSUE TITLE
Removing property that a prefab var relies on breaks the var UI.

### ISSUE THREAD

**Issue by youarereadingthis** [Facepunch/sbox-issues#6154] opened 2024-08-07 16:30 UTC
### Describe the bug

Removing a property from a component that a prefab variable relies on causes NREs in the scene editor and for the list to no longer show.

### To Reproduce

1. Create a component with inspector-listed properties.
2. Create a prefab and add that component to it.
3. Add prefab variables (using the star buttons) for those properties.
4. Remove one of the properties from the code of your component.

Watch as the prefab variable list does not show and there are NREs. There is no way in-UI I found to fix this.

### Expected behavior

The prefab var depending on a removed component property should be grayed out and/or have an emoji, and not completely break the var UI.

### Additional context

My solution was to manually edit the file to remove the references to the missing properties.

**Comment by solwllms** [comment] 2024-09-11 18:09
Duplicate of #6116

**Closed by solwllms** 2024-09-11 18:09 UTC
Labels: bug
