### ISSUE TITLE
Input event positioning incorrect after translating a panel

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#95] opened 2021-05-03 20:43 UTC
**Describe the bug**

Using transform:translateX(-50%) will move the element but hover & click events will still use the old position of the element (or children elements).

https://streamable.com/evttvx

**To Reproduce**

1. Create an element with position:absolute, fill it with panels like a grid.
2. Give it a transform:translateX()
3. Hover and click events will use the untranslated position of the element

```
public class InventoryGrid : SurvivalPanel
{

	public InventoryGrid()
	{
		RefreshItems();
	}

	private void RefreshItems()
	{
		Style.FlexWrap = Wrap.Wrap;
		Style.JustifyContent = Justify.SpaceBetween;

		for ( int i = 0; i < 80; i++ )
		{
			var slot = Add.Panel("slot");
			slot.AddEvent( "onclick", () => slot.Style.BackgroundColor = Color.Random );
		}
	}

}
```

```
inventorygrid {
	position: absolute;
	width: 888px;
	height: 294px;
	bottom: 32px;
	left: 50%;
	transform: translateX(-50%);
	background-color: rgba(black 0.75);
	padding: 12px;

	.slot {
		background-color: #263131;
		width: 50px;
		height: 50px;
		margin: 2px;

		&:hover {
			background-color: #FFF;
		}
	}
}
```

**Comment by Jake-Rich** [comment] 2021-05-03 20:47
Duplicate of #42?

**Closed** 2021-05-04 07:19 UTC
Labels: bug
