### ISSUE TITLE
Spring joint crashes physics engine

### ISSUE THREAD

**Issue by chelog** [Facepunch/sbox-issues#244] opened 2021-05-24 11:13 UTC
**Describe the bug**
Physics engine goes boom while creating spring joint

**To Reproduce**
Just create spring joint, tried different parameters, all give the same results
```cs
PhysicsJoint.Spring
    .From(ent1.PhysicsGroup.GetBody(0))
    .To(ent2.PhysicsGroup.GetBody(0))
    .Create();
```

**Expected behavior**
Not crashing 🤷‍♂️ 

**Video**
https://youtu.be/SJAvREZQugI

**Comment by aylaylay** [comment] 2021-05-25 00:21
This should be fixed now. It was caused by frequency being zero. I've set sensible defaults but also fixed it blowing up when frequency is zero.

**Comment by chelog** [comment] 2021-05-25 11:15
I've set frequency to higher than that when testing giving the same results. Will test now anyway

**Closed** 2021-05-25 11:17 UTC
Labels: bug, review
