### ISSUE TITLE
Glass shader is not displayed correctly in hammer, modeldoc and in game with open console

### ISSUE THREAD

**Issue by kote2345** [Facepunch/sbox-issues#1410] opened 2021-12-13 12:09 UTC
**Describe the bug**

Glass shader is not displayed correctly in hammer, modeldoc and in game with open console
Modeldoc: https://youtu.be/rrJ_CBLB6rE
Hammer: https://youtu.be/p94syahGOhM
Game with open console: ![image](https://user-images.githubusercontent.com/62496056/145809034-e4c40c0d-a5d9-4a68-a9f7-348ce415579c.png)

**To Reproduce**

1. Open in modeldoc model which uses material with glass shader or place this model in hammer
2. See error

**Expected behavior**

Glass should be displayed correctly

**Comment by DoctorGurke** [comment] 2021-12-13 12:13
I've noticed the latter on my post processing, too. Seems to be related to the new editor stuff messing with the uv calculation for the frame buffer.

**Comment by ogniK5377** [comment] 2021-12-14 12:31
Duplicate of #1204

**Closed by ogniK5377** 2021-12-14 12:31 UTC
Labels: bug
