### ISSUE TITLE
Automatic exposure is enabled on the thumbnail camera for model uploads

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4279] opened 2023-12-21 12:25 UTC
### Describe the bug

Automatic exposure is enabled on the thumbnail camera for model uploads

### To Reproduce

You can see it on all the recently uploaded models if you hover over them for a while, the videos don't loop correctly because of a change in exposure over time

### Expected behavior

no exposure change in thumbnail turnarounds

**Comment by MaxLebled** [comment] 2023-12-21 12:27
Duplicate of https://github.com/Facepunch/sbox-issues/issues/4270

**Closed by MaxLebled** 2023-12-21 12:27 UTC
Labels: bug
