### ISSUE TITLE
Cursor doesn't show up sometimes after opening the game menu

### ISSUE THREAD

**Issue by programneer** [Facepunch/sbox-issues#3978] opened 2023-09-06 12:15 UTC
### Describe the bug

When i was in-game, i opened an pause menu, heading to settings just in case to change something that fit well to me, and closed it, but then when i open up again when something doesn't do the good job, the cursor doesn't show up and to make cursor reappear, either when in editor press ` (tilde) to switch between console, open the console and type **open** or move around the cursor until reappear

### To Reproduce

1. Start any game
2. Open the game menu by pressing ESC
3. Click _ (minimize) button
4. Close it and wait a few seconds
5. Open it and see if the cursor is not showing
6. If it is, then close it and repeat the process again from step 2 to 3

### Expected behavior

The cursor should always appear

### Additional context

OS: Windows 11 (22621.2134)
PC Case: ASUS TUF GAMING F15 (lol)
CPU: Intel Core i5-10300H
GPU: NVIDIA GeForce GTX 1650
Primary Disk: (almost) 512 GB Micron
Secondary Disk: 256 GB Goodram CX400

**Comment by Phyksar** [comment] 2023-09-14 23:27
Here's the video reproducing the case, at the end the cursor finally appears, looks like it somehow depends on a screen position.

https://github.com/sboxgame/issues/assets/13320416/a79a4992-9a6e-4688-beaa-5780e8090f7b

**Comment by garrynewman** [comment] 2024-01-08 06:59
Thanks - but you're on the 3 month old branch - this is already fixed on the staging branch

**Closed by garrynewman** 2024-01-08 06:59 UTC
Labels: bug
