### ISSUE TITLE
Custom Input actions don't are not executed

### ISSUE THREAD

**Issue by Arslanich122** [Facepunch/sbox-issues#6615] opened 2024-10-15 20:28 UTC
### Describe the bug

I don’t know for sure if this is a bug, but I read in the documentation, there is nothing about this error. In the code, I made a condition based on a custom input action and it did not work, although I checked everything in the input settings and everything was correct there. After that, I replaced the custom input action with a built-in one (such as use, reload, attack 1, attack 2 and others) and after that the condition began to work.

### To Reproduce

To make a long story short, I wrote the code using a custom input action and it didn’t work, but with the built-in ones it worked.

### Expected behavior

Here I will explain in more detail, the code was supposed to output a certain phrase to the console, I added to the input settings I defined my own input action and the code did not work with it, but with the built-in input action (such as attack 1, attack 2, Forward, Backward, Left ,Right and others) the code worked and the phrase was displayed in the console

### Media/Files

![Image](https://github.com/user-attachments/assets/d562b965-8fdb-487b-a3b9-34f28c5ed4e6)
![Image](https://github.com/user-attachments/assets/e1393485-8fd8-4381-a6a7-9f13d70eabd7)

**Comment by Bozcx** [comment] 2024-10-15 20:32
Repost of this https://github.com/Facepunch/sbox-issues/issues/6599

**Comment by DevulTj** [comment] 2024-10-16 08:07
Closing this because it's a duplicate of another issue.

**Closed** 2024-10-16 08:07 UTC
