### ISSUE TITLE
Let developers mark events in Steam's new video recording feature

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#5745] opened 2024-06-29 12:15 UTC
### For?

S&Box

### What can't you do?

I think it'd be cool if developers could trigger something that makes s&box mark an event on the new beta Steam recording feature.
https://store.steampowered.com/gamerecording
https://partner.steamgames.com/doc/features/timeline

### How would you like it to work?

Probably something like `Sandbox.Services.RecordingEvent(Enum EventType)` or something?
The Steam API lists a bunch of different marker types on their docs page, these could be the event types.

### What have you tried?

The recording feature is still only on Steam's beta and probably only implemented in Valve's own games at the moment (I know L4D2 has it implemented because they use it in their example implementation video, probably CS2 as well), so it's a bit early days but I figured I'd make an issue for it so folks are made aware that it's a thing.

**Comment by aylaylay** [comment] 2024-06-29 12:16
Duplicate of #5731

**Closed by aylaylay** 2024-06-29 12:16 UTC
Labels: feature request
