### ISSUE TITLE
Skinned model renderer appears to render the last frame position and not current.

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#6650] opened 2024-10-21 09:55 UTC
### Describe the bug

When a skinned model renderer is set transform to the camera, either by worldpos/rot in prerender or just being a child of the camera. It will appear jittery when rotating/moving the camera as if it's a frame behind, when it should be in the same position.

### To Reproduce

1. make a camera rotate and move script
2. parent a model collider object and a skinned model collider object
3. see as the model collider stays perfectly in the same place on the screen at all times
4. and that the skinned model renderer is a frame behind.

### Expected behavior

being rendered at the right time after it's transform is changed.

### Media/Files

https://github.com/user-attachments/assets/a8344237-0bbf-472b-8a87-3da48e92f4a2

**Comment by SwagAccount** [comment] 2024-10-23 05:10
Is this not an issue?

**Comment by aylaylay** [comment] 2024-10-26 02:06
Works for me, please provide a repro

**Comment by SwagAccount** [comment] 2024-10-27 01:56
https://github.com/Softsplit/sandbox - for right now this is the only example I can find of the issue, and it's where it is occuring.

I will work on a new repo and try to recreate it.

**Comment by aylaylay** [comment] 2024-10-27 03:21
Should be fixed now

https://github.com/user-attachments/assets/66da8635-68e1-4502-aa46-a2f2f45c3f90

**Comment by aylaylay** [comment] 2024-10-27 04:45
Had to revert it for now

**Comment by SwagAccount** [comment] 2024-10-27 05:20
as long as I know that it will be fixed at some point

**Comment by aylaylay** [comment] 2024-10-27 05:41
Well the issue is that you're transforming the viewmodel at the wrong time. The viewmodel should be on camera and camera is moved in OnUpdate instead of OnPreRender.

The order goes:

1. Update
2. UpdateBones
3. PreRender

So you need to move the camera and move the skinned renderer to it before bone are updated.

**Comment by aylaylay** [comment] 2024-10-27 07:55
Should be good now

**Closed** 2024-10-31 04:50 UTC
