### ISSUE TITLE
Markdown support for Gamemode descriptions.

### ISSUE THREAD

**Issue by PixelQubed** [Facepunch/sbox-issues#2483] opened 2022-11-02 01:29 UTC
### For?

S&Box

### What can't you do?

We can't properly format the descriptions of game modes currently with like bold lettering or underlining, which makes descriptions look ugly.

### How would you like it to work?

Just like how GitHub's markdown works. Have buttons on the site but also allow the syntax in the editor online. Also, a preview of the final result would be nice too.

### What have you tried?

Nothing I can try other than adding huge spaces between paragraphs.

**Comment by ogniK5377** [comment] 2022-11-02 05:00
Duplicate of https://github.com/Facepunch/sbox-issues/issues/1113

**Closed by ogniK5377** 2022-11-02 05:00 UTC
Labels: feature
