### ISSUE TITLE
Scale the LOD distance with the gameobject scale

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#4933] opened 2024-02-22 21:40 UTC
### For?

S&Box

### What can't you do?

When scaling up a GameObject with a ModelRenderer, looking from far away the lowest LOD is shown even though the object is gigantic.

### How would you like it to work?

Scale the distance by the object scale, showing a higher quality LOD when it takes up more space.

### What have you tried?

Checking the attributes for forcing LODs

### Additional context

<img width="576" alt="1708637895646" src="https://github.com/Facepunch/sbox-issues/assets/1517911/cc2e322f-0ea1-4846-a46a-69f28884c944">

**Comment by yuberee** [comment] 2024-06-10 09:05
Duplicate of #2327 
Also bumping because it's pretty annoying.

**Comment by aylaylay** [comment] 2024-06-21 04:53
Lod distances are now scaled by the largest component value of the object scale

**Closed by aylaylay** 2024-06-21 04:53 UTC
Labels: feature request
