### ISSUE TITLE
Asset browser not clearing when a project is disabled.

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sbox-issues#3643] opened 2023-07-17 13:08 UTC
### Describe the bug

When projects are disabled (by switching a game project, or disabling a content project in content mode) it no longer shows under the project tab in the asset browser. (this is expected and what it should do.)

However the assets in this project are not being cleared from the asset browser, so still remain.

### To Reproduce

1. Have a content project that is enabled with content in it.
2. disable this project in project window
3. see that the project is no longer in the asset browser, but its assets can still be found when searching in Everything.

This happens with one game projects too like so.

1. open any game project (we will call this GAME1).
2. file -> close game project. (issue doesn't happen on restart, so you have to do it this way)
3. open a new game project (we will call this GAME2).
4. go to asset browser, clear the filters and such so searching will show EVERYTHING, search for any asset from GAME1.
5. GAME1 assets still appear but not correctly, if you open them the source files are not found but the content files still exist.
6. GAME2 assets exist perfectly fine though.

### Expected behaviour

When a project is disabled, in the projects window, or when closing a project.
It should have a check to clear all assets under said project out of the asset browser before becoming disabled.

**Comment by robotboy655** [comment] 2023-07-17 13:13
Duplicate of https://github.com/sboxgame/issues/issues/3642 ?

**Comment by NotGaylien** [comment] 2023-07-17 13:24
Its working differently.
In that one content mode is "mounting"? idk if thats the best word or fully loading the last game project in the asset browser, all its assets perfectly.
it has a tab for the last game project and all, basically like i open the game project, but without the game code loading.
like so
![image](https://github.com/sboxgame/issues/assets/82092361/ca97261e-347a-4e22-8e72-7b3d43149555)
Hamsteria is loaded (in asset browser) even though im in content mode.

in this its just remembering the content files but not properly.
it remembers the specific assets file path and all that.
But its not putting it under a actual project in the asset browser.
![image](https://github.com/sboxgame/issues/assets/82092361/c7f1c405-faac-4169-81de-48ca2a0e4a0a)
Every previous project assets still exist but they show up as errors

**Comment by NotGaylien** [comment] 2023-07-17 13:27
To sum it up.
https://github.com/sboxgame/issues/issues/3642
Is loading a Game Projects assets in content mode. and happens even if you close and re-open s&box.

https://github.com/sboxgame/issues/issues/3643
is remembering previously loaded assets but not re-loading. and if s&box is re-opened they are cleared.

**Comment by NotGaylien** [comment] 2023-07-20 18:19
Just messed around with this issue more.

im fairly certain my issue is a duplicate of 
https://github.com/sboxgame/issues/issues/2637

although its become alot more noticeable,
https://youtu.be/uU7XQsT-fmA

**Comment by DevulTj** [comment] 2024-04-04 10:41
Shouldn't be a thing anymore with how we handle projects

**Closed by DevulTj** 2024-04-04 10:41 UTC
Labels: bug, editor
