### ISSUE TITLE
ServerRpc property

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#833] opened 2021-08-31 20:19 UTC
**What can't you do?**
Do client to server RPCs easily without using Server commands (which is a sucky design)

**How would you like it to work?**
We can use [ClientRpc] for Server to Client
Let's allow [ServerRpc] for Client (With Authority) to Server

**What have you tried?**
Using ServerCmd with static methods. It works but it's painful to use if you want to make stuff i.e an inventory container system

**Comment by Adesii** [comment] 2021-08-31 20:22
Duplicate of #191

**Closed** 2021-09-01 09:41 UTC
Labels: feature
