### ISSUE TITLE
Solo/Mute options in mixer do nothing

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#6974] opened 2024-11-20 13:53 UTC
### Describe the bug

When muting a mixer, the mixer continue to play the sound

### To Reproduce

- Create a mixer
- Mute them
- Add a sound point in the scene and apply the mixer on it

### Expected behavior

The mixer must be muted

**Comment by Gmod4phun** [comment] 2024-11-20 14:47
duplicate of [#6476](https://github.com/Facepunch/sbox-issues/issues/6476)

**Comment by aylaylay** [comment] 2024-12-02 17:56
Done

**Closed by aylaylay** 2024-12-02 17:56 UTC
