### ISSUE TITLE
When swapping scene games it seems to not load the new game correctly until you restart the editor

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#4178] opened 2023-12-13 09:43 UTC
### Describe the bug

When swapping scene games it seems to not load the new game correctly until you restart the editor
I thought this sorta stuff was going to fix itself with engine integration but it seems not 
Any components you wrote that aren't native don't get loaded properly, and the game view doesn't show scene

### To Reproduce

1. start one scene game with components in it
2. close it and open a different scene game with different components in it
3. observe the console telling you typelibrary can't find components, and the game window showing the main menu instead of a scene

### Expected behavior

should just load everything correctly

**Comment by NotGaylien** [comment] 2023-12-14 12:42
I have saw a few more weird things i noticed tied into this...

I will provide 3 basic game projects below...

lets say for this entire issue you opened `test-1` in editor and then close the editor. 
`test-1` is now our last sessions opened project.
you re-open the editor...

### PROBLEMS I FOUND INVOLVING THIS
1 - it will load the assets and code of `test-1` no matter what project you choose **_(this is why restarting fixes this problem)_**
2 - it wont load assets or code of `test-2` or `test-3`, only `test-1` (with exception of next point)
3 - if you switch between projects in a certain way keeping editor open you can get only its code to load.
4 - if you get components to load from multiple projects them components wont be cleared out when switching projects

## reproductions
**reproduction - ONLY LOADING LAST OPENED PROJECT**

1. open editor and load test 1
2. close editor, re-open it.
3. try open a different project, (`test-2` or `test-3` will work)

you will see it doesn't load the scenes / assets from `test-2` or `test-3`, but you will see it load `test-1` code and assets.

**reproduction  - GETTING CODE TO LOAD**

... carry on from above
4. close the opened project (not the editor)
5. open `test-1` and close it again.
6. open `test-2` or `test-3` (or any scene project you want) and close it again.
7. open `test-1` and now add a component and search for a component it which ever other project you chose.
If they are not there repeat step 5-7 again.
You can also repeat step 5-7 choosing any game project and load components from many many projects at once.
Now you are stuck with all them components loaded in your component selector.


## content

[sbox-games.zip](https://github.com/Facepunch/sbox-issues/files/13673178/sbox-games.zip)
This contains 3 super basic game projects.
`test-1` `test-2` `test-3`
each project has 2 components named like so
`test_1_comp1` `test_1_comp2`
`test_2_comp1` `test_2_comp2`
`test_3_comp1` `test_3_comp2`
each project has the minimal scene with an object in them using the components from its own project.

(also really similar issue - https://github.com/Facepunch/sbox-issues/issues/4122)

**Comment by garrynewman** [comment] 2023-12-15 07:00
It would be good to totally re-initialize when we switch game projects.  This would mean closing down GameMenu completely and creating a new instance of it.

That might be drastic though. In reality we probably just need to reset the environment properly in GameMenu and in Editor.

**Comment by handsomematt** [comment] 2024-01-26 00:19
Removed changing projects in the same editor instance, #4593 is intended to make this stuff smoother

**Closed by handsomematt** 2024-01-26 00:19 UTC
Labels: bug
